# Objective Functions: A Simple Example with Matrix Factorisation.

### Modified by Mauricio A Álvarez, October 2018, 2019

### 6th October 2015 Neil D. Lawrence

In last week's class we saw how we could load in a data set to pandas and use it for some simple data processing. We computed various probabilities on the data and I encouraged you to think about what sort of probabilities you need for prediction. This week we are going to take a slightly different tack. 

Broadly speaking there are two dominating approaches to machine learning problems. We started to consider the first approach last week: constructing models based on defining the relationship between variables using probabilities. This week we will consider the second approach: which involves defining an *objective function* and optimizing it. 

What do we mean by an objective function? An objective function could be an *error function*, a *cost function* or a *benefit* function. In evolutionary computing they are called *fitness* functions. But the idea is always the same. We write down a mathematical equation which is then optimized to do the learning. The equation should be a function of the *data* and our model *parameters*. We have a choice when optimizing, either minimize or maximize. To avoid confusion, in the optimization field, we always choose to minimize the function. If we have a function that we would like to maximize, we simply choose to minimize the negative of that function. 

So for this lab session, we are going to ignore probabilities, but don't worry, they will return! 

This week we are going to try and build a simple movie recommender system using an objective function. To do this, the first thing I'd like you to do is to install some software we've written for sharing information across google documents.

## Open Data Science Software

In Sheffield we have written a suite of software tools for 'Open Data Science'. Open data science is an approach to sharing code, models and data that should make it easier for companies, health professionals and scientists to gain access to data science techniques. For some background on open data science you can read [this blog post](http://inverseprobability.com/2014/07/01/open-data-science/). The first thing we will do this week is to download that suite of software. 

The software can be installed using

```python
pip install pods
```

from the command prompt where you can access your python installation.


## Download the MovieLens 100k Data

We are going to download the [MovieLens 100k](http://files.grouplens.org/datasets/movielens/ml-latest-small-README.html) Data. This is a public dataset that contains 100,000 ratings and 3,600 tag applications applied to 9,000 movies by 600 users. When you use a data set that someone has prepared you should always reference the data source to acknowledge the work that's been placed in. This particular dataset was collected by the [Grouplens Research group](https://grouplens.org/),  at the University of Minnesota. For example, if you were to use this dataset for writing a paper, the authors ask you that you acknowledge their work by citing the following paper:

F. Maxwell Harper and Joseph A. Konstan. 2015. The MovieLens Datasets: History and Context. ACM Transactions on Interactive Intelligent Systems (TiiS) 5 (4):1-19 [https://doi.org/10.1145/2827872](https://doi.org/10.1145/2827872)

In [109]:
import pods
import zipfile
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pods.util.download_url("http://files.grouplens.org/datasets/movielens/ml-latest-small.zip")
zip_console = zipfile.ZipFile('ml-latest-small.zip', 'r')
for name in zip_console.namelist():
           zip_console.extract(name, './')

Downloading  http://files.grouplens.org/datasets/movielens/ml-latest-small.zip -> ./ml-latest-small.zip
[==============================]   0.933/0.933MB

### Question 1

Data ethics. If you find data available on the internet, can you simply use it without consequence? If you are given data by a fellow researcher can you publish that data on line?

#### Question 1 Answer

Write your answer to the question in this box.

Consent form

## Recommender Systems

A recommender system aims to make suggestions for items (films, books, other commercial products) given what it knows about users' tastes. The recommendation engine needs to represent the *taste* of all the users and the *characteristics* of each object. 

A common way for organizing objects is to place related objects spatially close together. For example in a library we try and put books that are on related topics near to each other on the shelves. One system for doing this is known as [Dewey Decimal Classification](http://en.wikipedia.org/wiki/Dewey_Decimal_Classification). In the Dewey Decimal Classification system (which dates from 1876) each subject is given a number (in fact it's a decimal number). For example, the field of Natural Sciences and Mathematics is given numbers which start with 500. Subjects based on Computer Science are given numbers which start 004 and works on the 'mathematical principles' of Computer science are given the series 004.0151 (which we might store as 4.0151 on a Computer). Whilst it's a classification system, the books in the library are typically laid out in the same order as the numbers, so we might expect that neighbouring numbers represent books that are related in subject. That seems to be exactly what we want when also representing films. Could we somehow represent each film's subject according to a number? In a similar way we could then imagine representing users with a list of numbers that represent things that each user is interested in.

Actually a one dimensional representation of a subject can be very awkward. To see this, let's have a look at the Dewey Decimal Classification numbers for the 900s, which is listed as 'History and Geography'. We will focus on subjects in the 940s which can be found in this list from [Wikipedia](https://en.wikipedia.org/wiki/List_of_Dewey_Decimal_classes#Class_900_%E2%80%93_History_&_geography). Whilst the ordering for places is somewhat sensible, it is also rather arbitrary. In the 940s we have Europe listed from 940-949, Asia listed from 950-959 and Africa listed from 960-969. Whilst it's true that Asia borders Europe, Africa is also very close, and the history of the Roman Empire spreads into [Carthage](http://en.wikipedia.org/wiki/Carthage) and later on Egypt. This image from Wikipedia shows a map of the Cathaginian Empire which fell after fighting with Rome. 


<a title="By Javierfv1212 [Public domain], from Wikimedia Commons" href="https://commons.wikimedia.org/wiki/File:Carthaginianempire.PNG"><img width="512" alt="Carthaginianempire" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Carthaginianempire.PNG/512px-Carthaginianempire.PNG"></a>

We now need to make a decision about whether Roman Histories are European or African, ideally we'd like them to be somewhere between the two, but we can't place them there in the Dewey Decimal system because between Europe and Africa is Asia, which has less to do with the Roman Empire than either Europe or Africa. Of course the fact that we've used a map provides a clue as to what to do next. Libraries are actually laid out on floors, so what if we were to use the spatial lay out to organise the sujbects of the books in two dimensions. Books on Geography could be laid out according to where in the world they are referring to. 

Such complexities are very hard to encapsulate in one number, but inspired by the map examples we can start considering how we might lay out films in two dimensions. Similarly, we can consider laying out a map of people's interests. If the two maps correspond to one another, the map of people could reflect where they might want to live in 'subject space'. We can think of representing people's tastes as where they might best like to sit in the library to access easily the books they are most interested in.


## Inner Products for Representing Similarity

Ideas like the above are good for gaining intuitions about what we might want, but the one of the skills of data science is representing those ideas mathematically. Mathematical abstraction of a problem is one of the key ways in which we've been able to progress as a society. Understanding planetary motions, as well as those of the smallest molecule (to quote Laplace's [Philosophical Essay on Probabilities](http://books.google.co.uk/books?id=1YQPAAAAQAAJ&printsec=frontcover&source=gbs_ge_summary_r&cad=0#v=onepage&q&f=false)) needed to be done mathematically. The right mathematical model in machine learning can be slightly more elusive, because constructing it is a two stage process. 

1. We have to determine the right intuition for the system we want to represent. Notions such as 'subject' and 'interest' are not mathematically well defined, and even when we create a new interpretation of what they might mean, each interpretation may have its own weaknesses. 

2. Once we have our interpretation we can attempt to mathematically formalize it. In our library interpretation, that's what we need to do next. 

### The Library on an Infinite Plane

Let's imagine a library which stores all the items  we are interested in, not just books, but films and shopping items too. Such a library is likely to be very large, so we'll create it on an infinite two dimensional plane. This means we can use all the real numbers to represent the location of each item on the plane. For a two dimensional plane, we need to store the locations in a vector of numbers: we can decide that the $j$th item's location in the library is given by 
$$
\mathbf{v}_j = \begin{bmatrix} v_{j,1} \\ v_{j,2}\end{bmatrix},
$$
where $v_{j,1}$ represents the $j$th item's location in the East-West direction (or the $x$-axis) and $v_{j,2}$ represents the $j$th item's location in the North-South direction (or the $y$-axis). Now we need to specify the location where each user sits so that all the items that interest them are nearby: we can also represent the $i$th user's location with a vector 
$$
\mathbf{u}_i = \begin{bmatrix} u_{i,1} \\ u_{i,2}\end{bmatrix}.
$$
Finally, we need some way of recording a given user's affinity for a given item. This affinity might be the rating that the user gives the film. We can use $y_{i,j}$ to represent user $i$'s affinity for item $j$. 

For our film example we might imagine wanting to order films in a few ways. We could imagine organising films in the North-South direction as to how romantic they are. We could place the more romantic films further North and the less romantic films further South. For the East-West direction we could imagine ordering them according to how historic they are: we can imagine placing science fiction films to the East and historical drama to the West. In this case, fans of historical romances would be based in the North-West location, whilst fans of Science Fiction Action films might be located in the South-East (if we assume that 'Action' is the opposite of 'Romance', which is not necessarily the case). How do we lay out all these films? Have we got the right axes? In machine learning the answer is to 'let the data speak'. Use the data to try and obtain such a lay out. To do this we first need to obtain the data.

## Obtaining the Data

As mentioned before, the MovieLens dataset that we'll use has 100,000 ratings to 9,000 movies by 600 users. For now, we will only work with a subset of the dataset. In particular, we will randomly chose a particular number of users and extract the movies and ratings that the users gave to those movies. Read the code below and understand what it is doing.

**Before you run the code**, notice that `YourStudentID` in the first line is a variable that will specify the seed for the random number generator that will select a particular set of `nUsersInExample` users. Change the number that has been assigned by default to `YourStudentID` to the last three digits of your UCard number. All of you will have a different subset of users.

In [110]:
YourStudentID = 20  # Include here the last three digits of your UCard number
nUsersInExample = 10 # The maximum number of Users we're going to analyse at one time

ratings = pd.read_csv("./ml-latest-small/ratings.csv") 
"""
ratings is a DataFrame with four columns: userId, movieId, rating and tags. We
first want to identify how many unique users there are. We can use the unique 
method in pandas
"""


indexes_unique_users = ratings['userId'].unique()
n_users = indexes_unique_users.shape[0]
""" 
We randomly select 'nUsers' users with their ratings. We first fix the seed
of the random generator to make sure that we always get the same 'nUsers'
"""
np.random.seed(YourStudentID)
indexes_users = np.random.permutation(n_users)
my_batch_users = indexes_users[0:nUsersInExample]
"""
We will use now the list of 'my_batch_users' to create a matrix Y. 
"""
# We need to make a list of the movies that these users have watched
list_movies_each_user = [[] for _ in range(nUsersInExample)]
list_ratings_each_user = [[] for _ in range(nUsersInExample)]
# Movies
list_movies = ratings['movieId'][ratings['userId'] == my_batch_users[0]].values
list_movies_each_user[0] = list_movies                    
# Ratings                      
list_ratings = ratings['rating'][ratings['userId'] == my_batch_users[0]].values
list_ratings_each_user[0] = list_ratings
# Users
n_each_user = list_movies.shape[0]
list_users = my_batch_users[0]*np.ones((1, n_each_user))

for i in range(1, nUsersInExample):
    # Movies
    local_list_per_user_movies = ratings['movieId'][ratings['userId'] == my_batch_users[i]].values
    list_movies_each_user[i] = local_list_per_user_movies
    list_movies = np.append(list_movies,local_list_per_user_movies)
    # Ratings                                 
    local_list_per_user_ratings = ratings['rating'][ratings['userId'] == my_batch_users[i]].values
    list_ratings_each_user[i] = local_list_per_user_ratings
    list_ratings = np.append(list_ratings, local_list_per_user_ratings)  
    # Users                                   
    n_each_user = local_list_per_user_movies.shape[0]                                                                               
    local_rep_user =  my_batch_users[i]*np.ones((1, n_each_user))    
    list_users = np.append(list_users, local_rep_user)

# Let us first see how many unique movies have been rated
indexes_unique_movies = np.unique(list_movies)


n_movies = indexes_unique_movies.shape[0]

# As it is expected no all users have rated all movies. We will build a matrix Y 
# with NaN inputs and fill according to the data for each user 
temp = np.empty((n_movies,nUsersInExample,))
temp[:] = np.nan
Y_with_NaNs = pd.DataFrame(temp)
for i in range(nUsersInExample):
 local_movies = list_movies_each_user[i]
 ixs = np.in1d(indexes_unique_movies, local_movies)
 Y_with_NaNs.loc[ixs, i] = list_ratings_each_user[i]

Y_with_NaNs.index = indexes_unique_movies.tolist()
Y_with_NaNs.columns = my_batch_users.tolist()


print(Y_with_NaNs.shape)
Y_with_NaNs

(600, 10)

        119  584  416  304  397  14   94   529  543  13
1       3.5  5.0  NaN  5.0  NaN  NaN  NaN  3.0  NaN  NaN
2       NaN  NaN  NaN  4.0  NaN  NaN  4.0  NaN  NaN  NaN
4       NaN  NaN  NaN  NaN  NaN  3.0  NaN  NaN  NaN  NaN
7       NaN  NaN  NaN  4.0  NaN  3.0  NaN  2.0  NaN  NaN
10      4.0  5.0  NaN  4.0  NaN  NaN  3.0  NaN  NaN  NaN
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
157699  4.5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
162350  4.5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
165551  4.5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
166461  4.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
168252  4.5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[600 rows x 10 columns]

### Question 2

Have a look at the matrix `Y_with_NaNs`. The movies data is now in a data frame which contains one column for each user rating the movie. There are some entries that contain 'NaN'. What does the 'NaN' mean in this context?

#### Answer Question 2

Write your answer to the question in this box.

Mean that they haven't rated that film

Now we will convert our data structure into a form that is appropriate for processing. We will convert the `Y_with_NaNs` dataframe into a new dataframe which contains the user, the movie, and the rating using the following code

In [111]:
p_list_ratings = np.concatenate(list_ratings_each_user).ravel()
p_list_ratings_original = p_list_ratings.tolist()
mean_ratings_train = np.mean(p_list_ratings)
p_list_ratings =  p_list_ratings - mean_ratings_train # remove the mean
p_list_movies = np.concatenate(list_movies_each_user).ravel().tolist()
p_list_users = list_users.tolist()
Y = pd.DataFrame({'users': p_list_users, 'movies': p_list_movies, 'ratingsorig': p_list_ratings_original,'ratings':p_list_ratings.tolist()})
Y

     users  movies  ratingsorig   ratings
0    119.0       1          3.5 -0.367718
1    119.0      10          4.0  0.132282
2    119.0      44          3.0 -0.867718
3    119.0     170          5.0  1.132282
4    119.0     173          3.0 -0.867718
..     ...     ...          ...       ...
819   13.0    3952          3.0 -0.867718
820   13.0    3977          3.0 -0.867718
821   13.0    3996          5.0  1.132282
822   13.0    4011          5.0  1.132282
823   13.0    4148          4.0  0.132282

[824 rows x 4 columns]

### Question 3

The dataframes `Y_with_NaNs` and `Y` contain the same information but organised in a different way. Explain what is the difference. We have also included two columns for ratings in dataframe `Y`, `ratingsorig` and `ratings`. Explain
the difference.

#### Question 3 Answer

in Y each row is a user rating

whereas Y_with_NaNs each row is a moive with its user ratings

## Measuring Similarity

We now need a measure for determining the similarity between the item and the user: how close the user is sitting to the item in the rooom if you like. We are going to use the inner product between the vector representing the item and the vector representing the user. 

An inner product (or [dot product](http://en.wikipedia.org/wiki/Dot_product)) between two vectors $\mathbf{a}$ and $\mathbf{b}$ is written as $\mathbf{a}\cdot\mathbf{b}$. Or in vector notation we sometimes write it as $\mathbf{a}^\top\mathbf{b}$. An inner product is simply the sume of the products of each element of the vector,
$$
\mathbf{a}^\top\mathbf{b} = \sum_{i} a_i b_i
$$
The inner product can be seen as a measure of similarity. The inner product gives us the cosine of the angle between the two vectors multiplied by their length. The smaller the angle between two vectors the larger the inner product. 
$$
\mathbf{a}^\top\mathbf{b} = |\mathbf{a}||\mathbf{b}| \cos(\theta)
$$
where $\theta$ is the angle between two vectors and $|\mathbf{a}|$ and $|\mathbf{b}|$ are the respective lengths of the two vectors.

Since we want each user to be sitting near each item, then we want the inner product to be large for any two items which are rated highly by that user. We can do this by trying to force the inner product $\mathbf{u}_i^\top\mathbf{v}_j$ to be similar to the rating given by the user, $y_{i,j}$. To ensure this we will use a least squares objective function for all user ratings.

## Objective Function

The error function (or objective function, or cost function) we will choose is known as 'sum of squares', we will aim to minimize the sum of squared squared error between the inner product of $\mathbf{u}_i$ and $\mathbf{v}_i$ and the observed score for the user/item pairing, given by $y_{i, j}$. 

The total objective function can be written as
$$
E(\mathbf{U}, \mathbf{V}) = \sum_{i,j} s_{i,j} (y_{i,j} - \mathbf{u}_i^\top \mathbf{v}_j)^2
$$
where $s_{i,j}$ is an *indicator* variable that is 1 if user $i$ has rated item $j$ and is zero otherwise. Here $\mathbf{U}$ is the matrix made up of all the vectors $\mathbf{u}$,
$$
\mathbf{U} = \begin{bmatrix} \mathbf{u}_1 \dots \mathbf{u}_n\end{bmatrix}^\top
$$
where we note that $i$th *row* of $\mathbf{U}$ contains the vector associated with the $i$th user and $n$ is the total number of users. This form of matrix is known as a *design matrix*. Similarly, we define the matrix
$$
\mathbf{V} = \begin{bmatrix} \mathbf{v}_1 \dots \mathbf{v}_m\end{bmatrix}^\top
$$
where again the $j$th row of $\mathbf{V}$ contains the vector associated with the $j$th item and $m$ is the total number of items in the data set.

## Objective Optimization

The idea is to mimimize this objective. A standard, simple, technique for minimizing an objective is *gradient descent* or *steepest descent*. In gradient descent we simply choose to update each parameter in the model by subtracting a multiple of the objective function's gradient with respect to the parameters. So for a parameter $u_{i,j}$ from the matrix $\mathbf{U}$ we would have an update as follows:
$$
u_{k,\ell} \leftarrow u_{k,\ell} - \eta \frac{\text{d} E(\mathbf{U}, \mathbf{V})}{\text{d}u_{k,\ell}} 
$$
where $\eta$ (which is pronounced *eta* in English) is a Greek letter representing the *learning rate*.  

We can compute the gradient of the objective function with respect to $u_{k,\ell}$ as
$$
\frac{\text{d}E(\mathbf{U}, \mathbf{V})}{\text{d}u_{k,\ell}} = -2 \sum_j s_{k,j}v_{j,\ell}(y_{k, j} - \mathbf{u}_k^\top\mathbf{v}_{j}). 
$$
Similarly each parameter $v_{i,j}$ needs to be updated according to its gradient.

### Question 4

What is the gradient of the objective function with respect to $v_{k, \ell}$? Write your answer in the box below, and explain which differentiation techniques you used to get there.

#### Question 4 Answer

Write your answer to the question in this box.

# Question 4 Code Answer
$$
\frac{\text{d}E(\mathbf{U}, \mathbf{V})}{\text{d}v_{k,\ell}} = -2 \sum_j s_{k,j}u_{j,\ell}(y_{k, j} - \mathbf{u}_k^\top\mathbf{v}_{j}). 
$$

## Steepest Descent Algorithm

In the steepest descent algorithm we aim to minimize the objective function by subtacting the gradient of the objective function from the parameters. 

### Initialisation

To start with though, we need initial values for the matrix $\mathbf{U}$ and the matrix $\mathbf{V}$. Let's create them as `pandas` data frames and initialise them randomly with small values.

In [122]:
q = 2 # the dimension of our map of the 'library'
learn_rate = 0.01
U = pd.DataFrame(np.random.normal(size=(nUsersInExample, q))*0.001, index=my_batch_users)
V = pd.DataFrame(np.random.normal(size=(n_movies, q))*0.001, index=indexes_unique_movies)

Now that we have the initial values set, we can start the optimization. First we define a function for the gradient of the objective and the objective function itself.

In [129]:
def objective_gradient(Y, U, V):
    gU = pd.DataFrame(np.zeros((U.shape)), index=U.index)
    gV = pd.DataFrame(np.zeros((V.shape)), index=V.index)
    obj = 0.
    nrows = Y.shape[0]
    for i in range(nrows):
        row = Y.iloc[i]
        user = row['users']
        film = row['movies']
        rating = row['ratings']
        prediction = np.dot(U.loc[user], V.loc[film]) # vTu
        diff = prediction - rating # vTu - y
        obj += diff*diff
        gU.loc[user] += 2*diff*V.loc[film]
        gV.loc[film] += 2*diff*U.loc[user]
    return obj, gU, gV

Now we can write our simple optimisation route. This allows us to observe the objective function as the optimization proceeds.

In [130]:
iterations = 30
for i in range(iterations):
    obj, gU, gV = objective_gradient(Y, U, V)
#     print("Iteration", i, "Objective function: ", obj)
#     print("Iteration", i, "gU: ", gU)
#     print("Iteration", i, "gV: ", gV)
    U -= learn_rate*gU
    V -= learn_rate*gV

0    0.000701
1    0.000549
Name: 1, dtype: float64
0   -0.000057
1    0.000313
Name: 10, dtype: float64
0   -0.001882
1    0.000999
Name: 44, dtype: float64
0   -0.002208
1    0.001407
Name: 170, dtype: float64
0    0.000947
1    0.000331
Name: 173, dtype: float64
0    0.000859
1   -0.000479
Name: 293, dtype: float64
0   -0.000143
1   -0.000265
Name: 296, dtype: float64
0   -0.000263
1    0.000086
Name: 315, dtype: float64
0   -0.001620
1    0.000016
Name: 318, dtype: float64
0    0.000122
1    0.000091
Name: 356, dtype: float64
0   -0.000515
1   -0.002288
Name: 364, dtype: float64
0    0.000271
1   -0.000122
Name: 434, dtype: float64
0    0.000108
1   -0.000792
Name: 442, dtype: float64
0   -0.000322
1   -0.000273
Name: 1092, dtype: float64
0   -0.000413
1   -0.000129
Name: 1270, dtype: float64
0   -0.000290
1   -0.000162
Name: 1580, dtype: float64
0   -0.000144
1   -0.000158
Name: 1732, dtype: float64
0    0.000129
1   -0.000072
Name: 2167, dtype: float64
0   -0.000462
1   -0.001762
Name: 2324, dtype: float64
0   -0.000413
1   -0.000225
Name: 2329, dtype: float64
0   -0.000405
1   -0.000665
Name: 2353, dtype: float64
0    0.000097
1   -0.000109
Name: 2571, dtype: float64
0   -0.000010
1    0.000081
Name: 2683, dtype: float64
0    0.000804
1   -0.000339
Name: 2701, dtype: float64
0    0.000060
1   -0.000516
Name: 3081, dtype: float64
0    0.000667
1   -0.002743
Name: 3147, dtype: float64
0    0.001314
1   -0.002536
Name: 3275, dtype: float64
0   -0.002090
1   -0.000949
Name: 3452, dtype: float64
0    0.004003
1    0.003673
Name: 3578, dtype: float64
0   -0.000268
1    0.000228
Name: 3793, dtype: float64
0    0.000095
1   -0.000017
Name: 4015, dtype: float64
0   -0.000976
1    0.000546
Name: 4148, dtype: float64
0    0.000079
1   -0.000352
Name: 4161, dtype: float64
0    0.000206
1    0.000172
Name: 4239, dtype: float64
0   -0.000842
1   -0.000499
Name: 4299, dtype: float64
0   -0.000360
1    0.000316
Name: 4306, dtype: float64
0   -0.000214
1    0.000014
Name: 4344, dtype: float64
0   -0.000142
1   -0.000023
Name: 4367, dtype: float64
0   -0.002085
1   -0.002630
Name: 4369, dtype: float64
0   -0.000188
1   -0.000256
Name: 4370, dtype: float64
0   -0.000941
1    0.000872
Name: 4387, dtype: float64
0    0.000570
1    0.000415
Name: 4446, dtype: float64
0    0.000172
1    0.000015
Name: 4643, dtype: float64
0   -0.000121
1   -0.000078
Name: 4718, dtype: float64
0    0.000186
1    0.000094
Name: 4776, dtype: float64
0   -0.001892
1    0.001944
Name: 4886, dtype: float64
0   -0.001202
1   -0.002632
Name: 4963, dtype: float64
0    0.000552
1   -0.002700
Name: 4993, dtype: float64
0    0.001164
1   -0.000990
Name: 4995, dtype: float64
0   -0.000378
1    0.000418
Name: 5010, dtype: float64
0    0.001251
1   -0.000796
Name: 5064, dtype: float64
0   -0.000438
1    0.000198
Name: 5218, dtype: float64
0    0.000081
1   -0.000634
Name: 5418, dtype: float64
0   -0.00031
1   -0.00020
Name: 5574, dtype: float64
0   -0.002418
1    0.003827
Name: 5810, dtype: float64
0   -0.003436
1   -0.000734
Name: 5952, dtype: float64
0   -0.001065
1    0.000740
Name: 5989, dtype: float64
0   -0.001555
1   -0.000396
Name: 5995, dtype: float64
0   -0.000164
1   -0.000307
Name: 6365, dtype: float64
0    0.000028
1   -0.000069
Name: 6377, dtype: float64
0   -0.000406
1    0.000158
Name: 6378, dtype: float64
0    0.000111
1   -0.000311
Name: 6539, dtype: float64
0   -0.001111
1   -0.000228
Name: 6934, dtype: float64
0    0.001763
1    0.005231
Name: 7153, dtype: float64
0    0.000515
1    0.000868
Name: 7454, dtype: float64
0   -0.000579
1   -0.001140
Name: 7458, dtype: float64
0   -0.000123
1    0.001537
Name: 8464, dtype: float64
0   -0.000647
1    0.000951
Name: 8622, dtype: float64
0    0.000345
1   -0.000057
Name: 8644, dtype: float64
0    0.000015
1    0.000508
Name: 8961, dtype: float64
0   -0.002959
1    0.000301
Name: 30707, dtype: float64
0   -0.000322
1   -0.000126
Name: 31410, dtype: float64
0    0.000406
1    0.000006
Name: 31685, dtype: float64
0    0.000338
1    0.000295
Name: 32587, dtype: float64
0    0.000135
1    0.000090
Name: 33615, dtype: float64
0    0.000085
1    0.000129
Name: 33660, dtype: float64
0    0.000464
1   -0.001197
Name: 33794, dtype: float64
0   -0.000298
1   -0.000236
Name: 35836, dtype: float64
0   -0.000218
1   -0.000062
Name: 40278, dtype: float64
0    0.000087
1   -0.000100
Name: 44022, dtype: float64
0   -0.000865
1    0.001250
Name: 44191, dtype: float64
0    0.000043
1   -0.000174
Name: 45517, dtype: float64
0    0.000132
1   -0.000317
Name: 46337, dtype: float64
0   -0.000332
1    0.000273
Name: 46723, dtype: float64
0   -0.000072
1    0.000096
Name: 47099, dtype: float64
0    0.000015
1    0.000072
Name: 48516, dtype: float64
0   -0.000052
1    0.000009
Name: 48774, dtype: float64
0    0.001479
1   -0.001414
Name: 49272, dtype: float64
0   -0.000075
1   -0.000278
Name: 50872, dtype: float64
0   -0.000017
1    0.000028
Name: 51077, dtype: float64
0   -0.000497
1    0.004721
Name: 51662, dtype: float64
0   -0.000904
1    0.000402
Name: 52722, dtype: float64
0   -0.000267
1    0.000968
Name: 54272, dtype: float64
0   -0.000186
1   -0.001011
Name: 54286, dtype: float64
0   -0.000153
1    0.000455
Name: 55247, dtype: float64
0   -0.001080
1   -0.000673
Name: 56174, dtype: float64
0    0.000234
1    0.000028
Name: 58559, dtype: float64
0    0.000084
1   -0.000328
Name: 59369, dtype: float64
0    0.000456
1   -0.000077
Name: 59784, dtype: float64
0   -0.000365
1    0.000503
Name: 60069, dtype: float64
0   -0.000192
1   -0.000853
Name: 60072, dtype: float64
0    0.000118
1   -0.000535
Name: 60074, dtype: float64
0    0.000144
1    0.001123
Name: 61323, dtype: float64
0   -0.001660
1    0.001592
Name: 63082, dtype: float64
0    0.000082
1   -0.000389
Name: 63113, dtype: float64
0   -0.003695
1   -0.001762
Name: 64614, dtype: float64
0    0.001078
1    0.001398
Name: 64839, dtype: float64
0   -0.001059
1   -0.002232
Name: 66097, dtype: float64
0   -0.001066
1   -0.001311
Name: 66511, dtype: float64
0   -0.001882
1    0.000547
Name: 67255, dtype: float64
0    0.000553
1   -0.000150
Name: 68157, dtype: float64
0   -0.000194
1    0.000044
Name: 68319, dtype: float64
0    0.001608
1    0.001661
Name: 68954, dtype: float64
0    0.002685
1    0.000164
Name: 69122, dtype: float64
0    0.000351
1   -0.000021
Name: 70286, dtype: float64
0    0.001906
1    0.001106
Name: 72998, dtype: float64
0   -0.000835
1   -0.000090
Name: 73017, dtype: float64
0   -0.001756
1    0.000374
Name: 73321, dtype: float64
0   -0.000130
1    0.000206
Name: 74458, dtype: float64
0   -0.000098
1    0.000174
Name: 76093, dtype: float64
0    0.000594
1    0.000364
Name: 78469, dtype: float64
0    0.000428
1    0.000390
Name: 78499, dtype: float64
0   -0.000837
1    0.000234
Name: 79091, dtype: float64
0    0.000064
1    0.000125
Name: 79132, dtype: float64
0   -0.004275
1    0.003569
Name: 80463, dtype: float64
0   -0.001683
1    0.001271
Name: 81229, dtype: float64
0   -0.000115
1    0.000010
Name: 81845, dtype: float64
0    0.000814
1    0.000158
Name: 82459, dtype: float64
0   -0.000087
1    0.000015
Name: 84392, dtype: float64
0   -0.000199
1   -0.001401
Name: 85020, dtype: float64
0    0.00021
1    0.00026
Name: 86882, dtype: float64
0    0.000675
1    0.001896
Name: 86911, dtype: float64
0   -0.000047
1   -0.000110
Name: 87232, dtype: float64
0   -0.000746
1    0.000050
Name: 87869, dtype: float64
0    0.000227
1   -0.000664
Name: 88163, dtype: float64
0   -0.000620
1   -0.000744
Name: 88744, dtype: float64
0   -0.001179
1    0.002006
Name: 89087, dtype: float64
0   -0.001176
1    0.001414
Name: 91529, dtype: float64
0   -0.000050
1   -0.000481
Name: 91542, dtype: float64
0   -0.001404
1   -0.001389
Name: 91658, dtype: float64
0   -0.000084
1   -0.000003
Name: 92259, dtype: float64
0   -0.000016
1    0.000215
Name: 95105, dtype: float64
0   -0.000523
1    0.000417
Name: 95441, dtype: float64
0    0.000690
1   -0.000896
Name: 96079, dtype: float64
0    0.000610
1   -0.000277
Name: 96861, dtype: float64
0    0.000026
1   -0.000171
Name: 99112, dtype: float64
0    0.000022
1   -0.000080
Name: 99114, dtype: float64
0   -0.000071
1   -0.000209
Name: 101142, dtype: float64
0   -0.000339
1    0.000054
Name: 102481, dtype: float64
0   -0.001487
1   -0.001566
Name: 102903, dtype: float64
0    0.000732
1   -0.002205
Name: 103141, dtype: float64
0   -0.000514
1   -0.000240
Name: 103335, dtype: float64
0   -0.001123
1   -0.004265
Name: 103984, dtype: float64
0    0.000112
1   -0.000681
Name: 104841, dtype: float64
0   -0.001560
1   -0.000603
Name: 104913, dtype: float64
0   -0.007025
1    0.000304
Name: 105504, dtype: float64
0    0.000175
1   -0.000221
Name: 105844, dtype: float64
0   -0.000228
1   -0.001387
Name: 106491, dtype: float64
0    0.000795
1   -0.001953
Name: 106782, dtype: float64
0    0.001774
1    0.001353
Name: 106918, dtype: float64
0   -0.004947
1   -0.001035
Name: 106920, dtype: float64
0   -0.000218
1    0.000141
Name: 108689, dtype: float64
0    0.000345
1   -0.000543
Name: 108932, dtype: float64
0    0.000331
1    0.000680

Name: 109374, dtype: float64
0   -0.003130
1    0.001901
Name: 109846, dtype: float64
0   -0.000261
1    0.000128
Name: 110718, dtype: float64
0    0.000111
1   -0.000196
Name: 110730, dtype: float64
0   -0.000360
1    0.000031
Name: 111781, dtype: float64
0   -0.002201
1   -0.002199
Name: 112183, dtype: float64
0    0.001260
1    0.001102
Name: 112552, dtype: float64
0    0.000510
1    0.000875
Name: 112868, dtype: float64
0    0.000354
1    0.000466
Name: 114184, dtype: float64
0    0.000475
1    0.004558
Name: 114662, dtype: float64
0   -0.000054
1    0.000153
Name: 114795, dtype: float64
0    0.000999
1   -0.000421
Name: 115149, dtype: float64
0   -0.001080
1    0.000449
Name: 115617, dtype: float64
0    0.000318
1   -0.000019
Name: 115713, dtype: float64
0   -0.002242
1    0.006114
Name: 116797, dtype: float64
0    0.000130
1   -0.000294
Name: 116823, dtype: float64
0    0.000240
1    0.000418
Name: 117176, dtype: float64
0    0.000144
1    0.000460
Name: 117533, dtype: float64
0    0.000298
1   -0.000243
Name: 117887, dtype: float64
0    0.000020
1    0.000565
Name: 119145, dtype: float64
0   -0.000741
1    0.000394
Name: 120635, dtype: float64
0   -0.000012
1    0.000093
Name: 122882, dtype: float64
0    0.000044
1   -0.000578
Name: 122904, dtype: float64
0    0.000149
1    0.000135
Name: 127184, dtype: float64
0   -0.002549
1    0.001112
Name: 128488, dtype: float64
0   -0.000874
1   -0.000674
Name: 128620, dtype: float64
0   -0.000107
1   -0.000125
Name: 129354, dtype: float64
0    0.000030
1   -0.001081
Name: 130520, dtype: float64
0    0.000183
1   -0.000203
Name: 130578, dtype: float64
0    0.000835
1   -0.001234
Name: 131023, dtype: float64
0    0.000174
1   -0.000120
Name: 131714, dtype: float64
0   -0.002231
1   -0.000649
Name: 132157, dtype: float64
0    0.000163
1    0.000175
Name: 134853, dtype: float64
0   -0.001525
1    0.001247
Name: 135532, dtype: float64
0    0.000312
1    0.001656
Name: 135861, dtype: float64
0   -0.000104
1   -0.000075
Name: 135887, dtype: float64
0    0.000077
1    0.000340
Name: 136562, dtype: float64
0   -0.007027
1    0.002293
Name: 136598, dtype: float64
0   -0.000631
1   -0.000138
Name: 136666, dtype: float64
0    0.000399
1    0.000476
Name: 138036, dtype: float64
0   -0.002107
1    0.001663
Name: 138210, dtype: float64
0   -0.000127
1   -0.000127
Name: 139385, dtype: float64
0   -0.000098
1    0.000375
Name: 139642, dtype: float64
0   -0.001654
1   -0.009198
Name: 140711, dtype: float64
0   -0.001111
1   -0.000351
Name: 141004, dtype: float64
0   -0.000208
1   -0.000507
Name: 142488, dtype: float64
0   -0.000204
1    0.002683
Name: 148626, dtype: float64
0    0.000724
1   -0.001807
Name: 157699, dtype: float64
0   -0.001334
1   -0.000777
Name: 162350, dtype: float64
0   -0.000267
1   -0.002266
Name: 165551, dtype: float64
0   -0.000396
1    0.000304
Name: 166461, dtype: float64
0   -0.000296
1   -0.000390
Name: 168252, dtype: float64
0   -0.002159
1   -0.001692
Name: 1, dtype: float64
0   -0.000484
1    0.002679
Name: 10, dtype: float64
0    0.002477
1   -0.001613
Name: 19, dtype: float64
0    0.000279
1    0.000283
Name: 22, dtype: float64
0   -0.001622
1    0.000351
Name: 34, dtype: float64
0    0.003507
1   -0.001872
Name: 39, dtype: float64
0    0.002249
1    0.002615
Name: 47, dtype: float64
0    0.003978
1    0.000852
Name: 48, dtype: float64
0    0.001740
1   -0.002176
Name: 60, dtype: float64
0   -0.000729
1    0.000688
Name: 110, dtype: float64
0   -0.001377
1   -0.002654
Name: 150, dtype: float64
0   -0.001446
1   -0.001940
Name: 153, dtype: float64
0    0.004489
1   -0.003129
Name: 158, dtype: float64
0   -0.001614
1    0.000953
Name: 160, dtype: float64
0   -0.001016
1   -0.006603
Name: 161, dtype: float64
0   -0.006090
1    0.004017
Name: 165, dtype: float64
0   -0.000144
1   -0.000051
Name: 173, dtype: float64
0    0.002571
1   -0.001806
Name: 185, dtype: float64
0   -0.002235
1    0.000041
Name: 186, dtype: float64
0   -0.000512
1   -0.011553
Name: 193, dtype: float64
0   -0.000278
1   -0.000131
Name: 196, dtype: float64
0   -0.001533
1    0.000031
Name: 203, dtype: float64
0    0.000214
1   -0.000113
Name: 204, dtype: float64
0   -0.000124
1   -0.000098
Name: 208, dtype: float64
0    0.000130
1    0.000408
Name: 218, dtype: float64
0    0.001551
1   -0.002359
Name: 225, dtype: float64
0    0.000212
1   -0.000274
Name: 227, dtype: float64
0    0.003729
1    0.002847
Name: 231, dtype: float64
0    0.007537
1   -0.002685
Name: 234, dtype: float64
0    0.000272
1   -0.000079
Name: 236, dtype: float64
0   -0.001845
1   -0.000509
Name: 237, dtype: float64
0   -0.000367
1   -0.000277
Name: 252, dtype: float64
0   -0.001691
1   -0.004504
Name: 253, dtype: float64
0    0.000316
1   -0.000057
Name: 256, dtype: float64
0    0.002203
1   -0.003000
Name: 257, dtype: float64
0    0.002743
1    0.000112
Name: 261, dtype: float64
0    0.000473
1    0.001373
Name: 276, dtype: float64
0    0.000907
1    0.001979
Name: 282, dtype: float64
0    0.001092
1    0.007850
Name: 288, dtype: float64
0   -0.002263
1    0.000882
Name: 292, dtype: float64
0   -0.000659
1    0.000367
Name: 293, dtype: float64
0    0.000935
1    0.001735
Name: 296, dtype: float64
0    0.000101
1    0.000137
Name: 300, dtype: float64
0   -0.002248
1    0.000737
Name: 315, dtype: float64
0    0.000840
1    0.001044
Name: 316, dtype: float64
0    0.000248
1   -0.000109
Name: 317, dtype: float64
0    0.000375
1   -0.000118
Name: 329, dtype: float64
0   -0.002184
1   -0.002052
Name: 337, dtype: float64
0    0.000542
1    0.000142
Name: 338, dtype: float64
0    0.000005
1    0.000174
Name: 339, dtype: float64
0    0.009201
1   -0.009633
Name: 344, dtype: float64
0    0.004026
1   -0.003682
Name: 349, dtype: float64
0    0.000063
1   -0.002885
Name: 350, dtype: float64
0    0.001041
1    0.000780
Name: 356, dtype: float64
0   -0.000515
1   -0.002288
Name: 364, dtype: float64
0    0.004533
1   -0.003314
Name: 367, dtype: float64
0    0.001711
1   -0.001313
Name: 377, dtype: float64
0   -0.001622
1    0.003650
Name: 380, dtype: float64
0   -0.000942
1    0.000701
Name: 410, dtype: float64
0   -0.000323
1   -0.000159
Name: 420, dtype: float64
0    0.002321
1   -0.001047
Name: 434, dtype: float64
0   -0.001619
1   -0.005165
Name: 435, dtype: float64
0    0.000180
1   -0.003793
Name: 440, dtype: float64
0    0.000928
1   -0.006782
Name: 442, dtype: float64
0   -0.001325
1    0.001699
Name: 454, dtype: float64
0    0.000332
1    0.000247
Name: 457, dtype: float64
0    0.000842
1   -0.002600
Name: 474, dtype: float64
0    0.000107
1    0.000021
Name: 477, dtype: float64
0   -0.000955
1   -0.002395
Name: 480, dtype: float64
0   -0.001700
1   -0.001241
Name: 500, dtype: float64
0    0.001729
1   -0.004354
Name: 508, dtype: float64
0    0.002057
1   -0.004921
Name: 539, dtype: float64
0    0.000198
1   -0.001955
Name: 585, dtype: float64
0    0.000123
1    0.000366
Name: 586, dtype: float64
0   -0.000808
1    0.001508
Name: 587, dtype: float64
0    0.000047
1   -0.000135
Name: 588, dtype: float64
0    0.002309
1    0.001017
Name: 589, dtype: float64
0   -0.001327
1   -0.003616
Name: 590, dtype: float64
0   -0.000781
1   -0.000084
Name: 592, dtype: float64
0    0.000419
1    0.000400
Name: 593, dtype: float64
0    0.001487
1    0.001150
Name: 595, dtype: float64
0   -0.000128
1    0.001257
Name: 597, dtype: float64
0   -0.001230
1    0.000127
Name: 736, dtype: float64
0    0.002668
1   -0.001699
Name: 170, dtype: float64
0    0.000054
1    0.000298
Name: 247, dtype: float64
0   -0.000885
1   -0.000148
Name: 260, dtype: float64
0   -0.000143
1   -0.000265
Name: 296, dtype: float64
0    0.002223
1   -0.000022
Name: 318, dtype: float64
0   -0.002602
1   -0.003282
Name: 319, dtype: float64
0   -0.000442
1    0.000282
Name: 327, dtype: float64
0   -0.001258
1   -0.000942
Name: 356, dtype: float64
0    0.001137
1   -0.000827
Name: 509, dtype: float64
0   -0.000270
1   -0.000339
Name: 527, dtype: float64
0    0.002304
1    0.002823
Name: 531, dtype: float64
0   -0.000568
1   -0.000212
Name: 608, dtype: float64
0    0.002222
1    0.000087
Name: 750, dtype: float64
0    0.003750
1    0.007486
Name: 830, dtype: float64
0   -0.000204
1   -0.004451
Name: 1196, dtype: float64
0   -0.000074
1   -0.000232
Name: 1199, dtype: float64
0    0.000062
1    0.000222
Name: 1206, dtype: float64
0    0.000157
1    0.000350
Name: 1219, dtype: float64
0   -0.000011
1   -0.000761
Name: 1296, dtype: float64
0    0.004089
1    0.002293
Name: 1580, dtype: float64
0    0.002853
1    0.008952
Name: 1721, dtype: float64
0   -0.002111
1    0.002365

Name: 2571, dtype: float64
0    0.003551
1    0.001114
Name: 2716, dtype: float64
0   -0.001870
1   -0.003945
Name: 2762, dtype: float64
0    0.002130
1   -0.000227
Name: 2858, dtype: float64
0   -0.000241
1   -0.000062
Name: 2959, dtype: float64
0   -0.003567
1   -0.002821
Name: 2997, dtype: float64
0    0.003973
1   -0.000252
Name: 3624, dtype: float64
0    0.000156
1   -0.000013
Name: 3677, dtype: float64
0    0.009164
1   -0.008043
Name: 4306, dtype: float64
0   -0.004103
1   -0.007998
Name: 4361, dtype: float64
0    0.000068
1    0.000264
Name: 4848, dtype: float64
0    0.010077
1   -0.010353
Name: 4886, dtype: float64
0    0.000337
1   -0.000079
Name: 4967, dtype: float64
0    0.000215
1   -0.000226
Name: 4973, dtype: float64
0   -0.00088
1   -0.00002
Name: 4979, dtype: float64
0   -0.001406
1    0.001196
Name: 4995, dtype: float64
0    0.000057
1   -0.000632
Name: 5303, dtype: float64
0   -0.000496
1   -0.004690
Name: 5445, dtype: float64
0   -0.000846
1    0.001443
Name: 5617, dtype: float64
0   -0.000010
1    0.000167
Name: 5902, dtype: float64
0    0.000864
1    0.000047
Name: 5951, dtype: float64
0    0.007432
1    0.001587
Name: 5952, dtype: float64
0    0.004167
1    0.007827
Name: 6365, dtype: float64
0   -0.001566
1    0.004390
Name: 6539, dtype: float64
0   -0.000323
1    0.000232
Name: 6874, dtype: float64
0   -0.001198
1    0.000407
Name: 7323, dtype: float64
0    0.006434
1    0.000878
Name: 8360, dtype: float64
0   -0.000033
1    0.000555
Name: 8959, dtype: float64
0    0.003529
1   -0.002748
Name: 26810, dtype: float64
0   -0.000367
1   -0.002420
Name: 46976, dtype: float64
0   -0.002159
1   -0.001692
Name: 1, dtype: float64
0   -0.000274
1    0.000130
Name: 2, dtype: float64
0   -0.000582
1   -0.000015
Name: 7, dtype: float64
0   -0.000057
1    0.000313
Name: 10, dtype: float64
0    0.001164
1   -0.000569
Name: 11, dtype: float64
0   -0.000056
1   -0.000131
Name: 13, dtype: float64
0    0.001737
1    0.000378
Name: 17, dtype: float64
0    0.000055
1    0.000157
Name: 21, dtype: float64
0   -0.000539
1   -0.000702
Name: 32, dtype: float64
0    0.002029
1    0.000176
Name: 36, dtype: float64
0    0.001336
1   -0.000270
Name: 46, dtype: float64
0    0.000147
1    0.000256
Name: 58, dtype: float64
0   -0.004408
1    0.005510
Name: 60, dtype: float64
0   -0.000717
1   -0.002132
Name: 62, dtype: float64
0    0.000539
1    0.000782
Name: 73, dtype: float64
0   -0.000013
1   -0.000352
Name: 81, dtype: float64
0    0.002629
1   -0.002167
Name: 86, dtype: float64
0   -0.003304
1   -0.000984
Name: 105, dtype: float64
0   -0.000729
1    0.000688
Name: 110, dtype: float64
0    0.004772
1   -0.001264
Name: 112, dtype: float64
0   -0.000165
1   -0.000440
Name: 135, dtype: float64
0   -0.001274
1   -0.001493
Name: 141, dtype: float64
0   -0.001377
1   -0.002654
Name: 150, dtype: float64
0   -0.000077
1   -0.000191
Name: 151, dtype: float64
0   -0.001446
1   -0.001940
Name: 153, dtype: float64
0   -0.000712
1    0.000469
Name: 165, dtype: float64
0    0.000660
1   -0.000181
Name: 168, dtype: float64
0   -0.002685
1   -0.000040
Name: 172, dtype: float64
0    0.000947
1    0.000331
Name: 173, dtype: float64
0    0.000300
1   -0.000211
Name: 185, dtype: float64
0   -0.000124
1   -0.000098
Name: 208, dtype: float64
0   -0.000526
1   -0.000857
Name: 222, dtype: float64
0   -0.003619
1   -0.000417
Name: 224, dtype: float64
0   -0.000367
1   -0.000277
Name: 252, dtype: float64
0   -0.000244
1    0.000012
Name: 258, dtype: float64
0    0.001155
1    0.000194
Name: 260, dtype: float64
0    0.000320
1    0.000013
Name: 261, dtype: float64
0    0.000414
1    0.000199
Name: 266, dtype: float64
0    0.001092
1    0.007850
Name: 288, dtype: float64
0    0.000100
1   -0.000056
Name: 293, dtype: float64
0   -0.001221
1   -0.002264
Name: 296, dtype: float64
0   -0.002982
1    0.000187
Name: 303, dtype: float64
0    0.000009
1    0.000216
Name: 314, dtype: float64
0   -0.000339
1    0.000003
Name: 318, dtype: float64
0    0.000375
1   -0.000118
Name: 329, dtype: float64
0    0.000542
1    0.000142
Name: 338, dtype: float64
0    0.00047
1   -0.00043
Name: 349, dtype: float64
0    0.001041
1    0.000780
Name: 356, dtype: float64
0    0.004437
1    0.001378
Name: 357, dtype: float64
0    0.000850
1    0.003775
Name: 364, dtype: float64
0   -0.000056
1   -0.000005
Name: 368, dtype: float64
0   -0.001311
1    0.001006
Name: 377, dtype: float64
0   -0.000190
1    0.000426
Name: 380, dtype: float64
0    0.000180
1   -0.003793
Name: 440, dtype: float64
0   -0.000711
1    0.005197
Name: 442, dtype: float64
0    0.002842
1    0.002115
Name: 457, dtype: float64
0    0.000842
1   -0.002600
Name: 474, dtype: float64
0   -0.000112
1   -0.000280
Name: 480, dtype: float64
0    0.000050
1   -0.000884
Name: 491, dtype: float64
0    0.004306
1    0.003143
Name: 500, dtype: float64
0    0.000706
1   -0.001394
Name: 524, dtype: float64
0    0.000832
1    0.001045
Name: 527, dtype: float64
0    0.000980
1    0.000172
Name: 529, dtype: float64
0    0.000240
1   -0.000575
Name: 539, dtype: float64
0    0.000360
1   -0.000326
Name: 541, dtype: float64
0   -0.000090
1   -0.000362
Name: 552, dtype: float64
0    0.000123
1    0.000366
Name: 586, dtype: float64
0    0.000047
1   -0.000135
Name: 588, dtype: float64
0    0.002309
1    0.001017
Name: 589, dtype: float64
0   -0.001327
1   -0.003616
Name: 590, dtype: float64
0    0.000419
1    0.000400
Name: 593, dtype: float64
0    0.001487
1    0.001150
Name: 595, dtype: float64
0    0.000020
1   -0.000192
Name: 597, dtype: float64
0    0.000390
1    0.000219
Name: 640, dtype: float64
0   -0.000210
1   -0.000038
Name: 647, dtype: float64
0   -0.000038
1   -0.000208
Name: 648, dtype: float64
0   -0.000380
1   -0.000272
Name: 653, dtype: float64
0    0.000081
1    0.000010
Name: 707, dtype: float64
0    0.000273
1   -0.000224
Name: 708, dtype: float64
0    0.000223
1    0.000034
Name: 733, dtype: float64
0   -0.000562
1    0.000116
Name: 780, dtype: float64
0    0.002471
1   -0.001857
Name: 784, dtype: float64
0    0.000185
1    0.000954
Name: 786, dtype: float64
0   -0.000187
1    0.000035
Name: 802, dtype: float64
0   -0.001802
1   -0.006137
Name: 809, dtype: float64
0   -0.001031
1   -0.000751
Name: 832, dtype: float64
0    0.000790
1    0.002815
Name: 836, dtype: float64
0    0.000313
1    0.000190
Name: 902, dtype: float64
0   -0.000415
1    0.000284
Name: 924, dtype: float64
0   -0.000539
1   -0.000022
Name: 944, dtype: float64
0    0.000559
1    0.001675
Name: 954, dtype: float64
0   -0.000702
1    0.001861
Name: 1007, dtype: float64
0    0.000160
1   -0.000898
Name: 1019, dtype: float64
0    0.000183
1    0.000070
Name: 1025, dtype: float64
0    0.000124
1    0.000292
Name: 1028, dtype: float64
0    0.000033
1    0.000557
Name: 1035, dtype: float64
0   -0.000105
1   -0.000051
Name: 1036, dtype: float64
0   -0.000485
1   -0.003125
Name: 1047, dtype: float64
0   -0.002561
1    0.000960
Name: 1057, dtype: float64
0    0.000058
1   -0.000321
Name: 1060, dtype: float64
0   -0.001127
1    0.000051
Name: 1064, dtype: float64
0    0.000370
1    0.000267
Name: 1073, dtype: float64
0    0.003548
1   -0.000292
Name: 1079, dtype: float64
0    0.001783
1   -0.000277
Name: 1097, dtype: float64
0   -0.001226
1    0.001972
Name: 1100, dtype: float64
0    0.000090
1   -0.000379
Name: 1101, dtype: float64
0    0.000278
1   -0.000119
Name: 1136, dtype: float64
0   -0.000659
1   -0.000737
Name: 1183, dtype: float64
0    0.000124
1    0.002699
Name: 1196, dtype: float64
0   -0.003199
1    0.001913
Name: 1197, dtype: float64
0    0.001410
1    0.000984
Name: 1198, dtype: float64
0    0.000191
1   -0.000012
Name: 1200, dtype: float64
0   -0.000121
1    0.000227
Name: 1207, dtype: float64
0    0.002914
1   -0.004285
Name: 1210, dtype: float64
0   -0.000644
1    0.000515
Name: 1214, dtype: float64
0    0.000089
1    0.000395
Name: 1220, dtype: float64
0    0.002391
1   -0.001812
Name: 1240, dtype: float64
0    0.001446
1    0.000202
Name: 1242, dtype: float64
0    0.000186
1    0.000161
Name: 1247, dtype: float64
0   -0.000602
1   -0.000783
Name: 1259, dtype: float64
0   -0.001000
1    0.003511
Name: 1265, dtype: float64
0   -0.003539
1   -0.001101
Name: 1270, dtype: float64
0    0.000020
1    0.000426
Name: 1275, dtype: float64
0    0.000803
1    0.000073
Name: 1291, dtype: float64
0   -0.000322
1    0.000126

Name: 1297, dtype: float64
0    0.000485
1   -0.000037
Name: 1302, dtype: float64
0   -0.000078
1   -0.000605
Name: 1307, dtype: float64
0    0.000214
1   -0.000202
Name: 1320, dtype: float64
0   -0.001506
1    0.001003
Name: 1356, dtype: float64
0   -0.000072
1    0.000339
Name: 1370, dtype: float64
0    0.000505
1    0.000375
Name: 1371, dtype: float64
0    0.003863
1   -0.002677
Name: 1372, dtype: float64
0   -0.001009
1    0.001359
Name: 1373, dtype: float64
0   -0.004231
1   -0.000886
Name: 1374, dtype: float64
0    0.000938
1    0.000608
Name: 1375, dtype: float64
0   -0.000970
1   -0.000668
Name: 1376, dtype: float64
0    0.003414
1   -0.008930
Name: 1377, dtype: float64
0    0.000562
1    0.000191
Name: 1380, dtype: float64
0   -0.001719
1   -0.000966
Name: 1385, dtype: float64
0   -0.000503
1    0.000370
Name: 1387, dtype: float64
0   -0.001618
1    0.001569
Name: 1391, dtype: float64
0   -0.001970
1    0.000329
Name: 1393, dtype: float64
0    0.000028
1   -0.000478
Name: 1396, dtype: float64
0    0.00019
1    0.00131
Name: 1407, dtype: float64
0   -0.001389
1   -0.000826
Name: 1408, dtype: float64
0    0.002978
1   -0.000941
Name: 1466, dtype: float64
0   -0.000133
1   -0.000203
Name: 1485, dtype: float64
0   -0.000131
1   -0.000001
Name: 1500, dtype: float64
0    0.008409
1   -0.008151
Name: 1517, dtype: float64
0   -0.000065
1   -0.000206
Name: 1527, dtype: float64
0    0.002872
1    0.000935
Name: 1544, dtype: float64
0   -0.000049
1   -0.000529
Name: 1552, dtype: float64
0    0.001538
1    0.002378
Name: 1566, dtype: float64
0    0.001019
1    0.000407
Name: 1569, dtype: float64
0    0.000020
1   -0.000019
Name: 1573, dtype: float64
0   -0.002479
1   -0.001390
Name: 1580, dtype: float64
0   -0.002505
1   -0.003050
Name: 1584, dtype: float64
0    0.002571
1    0.000515
Name: 1587, dtype: float64
0   -0.001145
1   -0.002848
Name: 1594, dtype: float64
0   -0.001066
1    0.000124
Name: 1608, dtype: float64
0   -0.002764
1    0.002586
Name: 1610, dtype: float64
0    0.000266
1   -0.000166
Name: 1616, dtype: float64
0    0.000154
1    0.000548
Name: 1653, dtype: float64
0   -0.000214
1   -0.000317
Name: 1676, dtype: float64
0   -0.000201
1   -0.001195
Name: 1680, dtype: float64
0   -0.000076
1    0.000265
Name: 1682, dtype: float64
0    0.000741
1   -0.004829
Name: 1686, dtype: float64
0    0.000195
1    0.000182
Name: 1688, dtype: float64
0    0.001552
1   -0.002527
Name: 1690, dtype: float64
0   -0.000139
1    0.000048
Name: 1704, dtype: float64
0    0.001617
1    0.000379
Name: 1717, dtype: float64
0   -0.000959
1   -0.003010
Name: 1721, dtype: float64
0   -0.000338
1    0.001143
Name: 1722, dtype: float64
0    0.001174
1   -0.000157
Name: 1726, dtype: float64
0    0.002316
1    0.000889
Name: 1747, dtype: float64
0   -0.000071
1   -0.000090
Name: 1777, dtype: float64
0    0.000722
1   -0.001017
Name: 1855, dtype: float64
0    0.000066
1   -0.000549
Name: 1876, dtype: float64
0    0.000652
1    0.002998
Name: 1882, dtype: float64
0    0.000105
1    0.000375
Name: 1907, dtype: float64
0   -0.000183
1    0.000073
Name: 1909, dtype: float64
0   -0.000202
1    0.000405
Name: 2006, dtype: float64
0    0.000053
1   -0.000053
Name: 2019, dtype: float64
0   -0.001316
1   -0.002305
Name: 2028, dtype: float64
0   -0.000226
1    0.000152
Name: 2141, dtype: float64
0   -0.000018
1   -0.000696
Name: 2279, dtype: float64
0   -0.002299
1    0.000103
Name: 2294, dtype: float64
0   -0.000095
1    0.000244
Name: 2316, dtype: float64
0    0.000365
1   -0.000061
Name: 2320, dtype: float64
0    0.003367
1   -0.002645
Name: 2321, dtype: float64
0   -0.000098
1   -0.000018
Name: 2322, dtype: float64
0    0.001783
1   -0.000919
Name: 2393, dtype: float64
0   -0.000287
1   -0.000205
Name: 2396, dtype: float64
0    0.000020
1    0.000053
Name: 2424, dtype: float64
0    0.000186
1    0.000178
Name: 2431, dtype: float64
0    0.000209
1    0.000163
Name: 2433, dtype: float64
0   -0.000210
1   -0.000066
Name: 2490, dtype: float64
0    0.001108
1   -0.002459
Name: 2496, dtype: float64
0    0.002485
1   -0.001433
Name: 2501, dtype: float64
0   -0.002602
1   -0.000522
Name: 2502, dtype: float64
0   -0.000109
1   -0.000343
Name: 2549, dtype: float64
0    0.000025
1    0.000366
Name: 2567, dtype: float64
0    0.000097
1   -0.000109
Name: 2571, dtype: float64
0   -0.000291
1   -0.000291
Name: 2605, dtype: float64
0    0.000014
1    0.001314
Name: 2628, dtype: float64
0    0.000804
1   -0.000339
Name: 2701, dtype: float64
0   -0.000241
1    0.000501
Name: 2761, dtype: float64
0   -0.002553
1   -0.005387
Name: 2762, dtype: float64
0    0.010818
1   -0.001153
Name: 2858, dtype: float64
0   -0.001270
1   -0.003512
Name: 2906, dtype: float64
0    0.002733
1    0.002162
Name: 2997, dtype: float64
0    0.002369
1   -0.000940
Name: 3052, dtype: float64
0   -0.000191
1   -0.001763
Name: 3114, dtype: float64
0   -0.002773
1    0.000766
Name: 3155, dtype: float64
0    0.000326
1    0.001169
Name: 3175, dtype: float64
0    0.000007
1    0.000247
Name: 5060, dtype: float64
0   -0.001406
1   -0.001414
Name: 123, dtype: float64
0   -0.001343
1   -0.000877
Name: 232, dtype: float64
0   -0.000989
1   -0.002477
Name: 492, dtype: float64
0    0.000465
1    0.000018
Name: 750, dtype: float64
0    0.000406
1    0.000406
Name: 1077, dtype: float64
0   -0.001296
1    0.000712
Name: 1104, dtype: float64
0   -0.000722
1   -0.003115
Name: 1230, dtype: float64
0   -0.002352
1   -0.000637
Name: 1244, dtype: float64
0    0.000442
1   -0.000027
Name: 1701, dtype: float64
0   -0.001528
1    0.000766
Name: 1953, dtype: float64
0   -0.003003
1    0.001428
Name: 2359, dtype: float64
0   -0.000220
1   -0.004655
Name: 2371, dtype: float64
0    0.005698
1    0.004835
Name: 3388, dtype: float64
0   -0.000100
1    0.000196
Name: 4017, dtype: float64
0    0.000560
1    0.000427
Name: 4037, dtype: float64
0   -0.000149
1   -0.000316
Name: 5291, dtype: float64
0    0.000566
1   -0.003637
Name: 5650, dtype: float64
0   -0.000084
1   -0.000351
Name: 6016, dtype: float64
0    0.000180
1   -0.000192
Name: 6993, dtype: float64
0   -0.000321
1    0.000002
Name: 8042, dtype: float64
0   -0.000062
1    0.000277
Name: 8228, dtype: float64
0   -0.000242
1    0.000119
Name: 8645, dtype: float64
0    0.000311
1    0.000034
Name: 44555, dtype: float64
0    0.001237
1    0.000617
Name: 4, dtype: float64
0    0.003820
1    0.000101
Name: 7, dtype: float64
0    0.008185
1   -0.005330
Name: 19, dtype: float64
0   -0.000104
1    0.000160
Name: 25, dtype: float64
0   -0.000539
1   -0.000702
Name: 32, dtype: float64
0    0.001061
1   -0.000567
Name: 39, dtype: float64
0    0.002249
1    0.002615
Name: 47, dtype: float64
0    0.006469
1    0.005302
Name: 95, dtype: float64
0   -0.003304
1   -0.000984
Name: 105, dtype: float64
0   -0.000729
1    0.000688
Name: 110, dtype: float64
0   -0.000161
1   -0.000310
Name: 150, dtype: float64
0   -0.003112
1   -0.004176
Name: 153, dtype: float64
0   -0.000155
1   -0.003496
Name: 193, dtype: float64
0    0.001732
1    0.001323
Name: 231, dtype: float64
0    0.003543
1    0.001700
Name: 266, dtype: float64
0    0.000907
1    0.001979
Name: 282, dtype: float64
0   -0.000050
1   -0.000362
Name: 288, dtype: float64
0    0.000935
1    0.001735
Name: 296, dtype: float64
0    0.002223
1   -0.000022
Name: 318, dtype: float64
0    0.002850
1    0.002678
Name: 337, dtype: float64
0    0.000005
1    0.000174
Name: 339, dtype: float64
0    0.005993
1   -0.006274
Name: 344, dtype: float64
0   -0.001190
1    0.004313
Name: 351, dtype: float64
0    0.000122
1    0.000091
Name: 356, dtype: float64
0    0.014981
1   -0.010953
Name: 367, dtype: float64
0    0.000020
1    0.000131
Name: 376, dtype: float64
0   -0.001311
1    0.001006
Name: 377, dtype: float64
0   -0.000131
1   -0.000054
Name: 383, dtype: float64
0    0.000271
1   -0.000122
Name: 434, dtype: float64
0   -0.001563
1   -0.000703
Name: 448, dtype: float64
0    0.001356
1   -0.000847
Name: 455, dtype: float64
0    0.000107
1    0.000021
Name: 477, dtype: float64
0    0.000732
1    0.001835
Name: 480, dtype: float64
0   -0.000331
1    0.005800
Name: 491, dtype: float64
0   -0.001325
1    0.003337
Name: 508, dtype: float64
0    0.002037
1   -0.001480
Name: 509, dtype: float64
0   -0.000541
1    0.001068
Name: 524, dtype: float64
0   -0.000638
1   -0.000801
Name: 527, dtype: float64
0    0.000240
1   -0.000575
Name: 539, dtype: float64
0    0.000680
1   -0.001173
Name: 540, dtype: float64
0    0.000592
1    0.002375
Name: 552, dtype: float64
0   -0.000195
1   -0.000067
Name: 553, dtype: float64
0   -0.000806
1   -0.002403
Name: 586, dtype: float64
0   -0.000155
1   -0.000422
Name: 590, dtype: float64
0   -0.001681
1   -0.000180
Name: 592, dtype: float64
0    0.000419
1    0.000400
Name: 593, dtype: float64
0   -0.000128
1    0.001257
Name: 597, dtype: float64
0    0.003794
1   -0.002851
Name: 784, dtype: float64
0   -0.000274
1    0.000130
Name: 2, dtype: float64

0    0.000371
1   -0.002053
Name: 10, dtype: float64
0   -0.000892
1    0.000436
Name: 11, dtype: float64
0    0.005741
1    0.001250
Name: 17, dtype: float64
0    0.005331
1   -0.003471
Name: 19, dtype: float64
0   -0.000360
1   -0.001032
Name: 21, dtype: float64
0   -0.004612
1   -0.006013
Name: 32, dtype: float64
0    0.000247
1   -0.000054
Name: 34, dtype: float64
0    0.003507
1   -0.001872
Name: 39, dtype: float64
0   -0.006219
1    0.003302
Name: 44, dtype: float64
0   -0.003711
1   -0.004314
Name: 47, dtype: float64
0   -0.004958
1   -0.004063
Name: 95, dtype: float64
0   -0.000729
1    0.000688
Name: 110, dtype: float64
0   -0.000161
1   -0.000310
Name: 150, dtype: float64
0   -0.001446
1   -0.001940
Name: 153, dtype: float64
0    0.001237
1   -0.000730
Name: 160, dtype: float64
0   -0.000119
1   -0.000771
Name: 161, dtype: float64
0   -0.000711
1    0.000469
Name: 165, dtype: float64
0   -0.004242
1    0.002980
Name: 185, dtype: float64
0    0.001748
1    0.001379
Name: 208, dtype: float64
0   -0.001188
1    0.001808
Name: 225, dtype: float64
0    0.001732
1    0.001323
Name: 231, dtype: float64
0   -0.005590
1   -0.014885
Name: 253, dtype: float64
0   -0.002715
1   -0.001303
Name: 266, dtype: float64
0   -0.000695
1   -0.001517
Name: 282, dtype: float64
0    0.000711
1    0.005113
Name: 288, dtype: float64
0    0.001734
1   -0.000676
Name: 292, dtype: float64
0   -0.000143
1   -0.000265
Name: 296, dtype: float64
0   -0.000128
1   -0.000159
Name: 316, dtype: float64
0   -0.001625
1    0.000718
Name: 317, dtype: float64
0   -0.002901
1    0.000029
Name: 318, dtype: float64
0    0.000375
1   -0.000118
Name: 329, dtype: float64
0   -0.002184
1   -0.002052
Name: 337, dtype: float64
0    0.002784
1   -0.002915
Name: 344, dtype: float64
0   -0.000798
1   -0.000598
Name: 356, dtype: float64
0   -0.011238
1   -0.003491
Name: 357, dtype: float64
0   -0.000060
1   -0.000267
Name: 364, dtype: float64
0    0.004533
1   -0.003314
Name: 367, dtype: float64
0   -0.001311
1    0.001006
Name: 377, dtype: float64
0    0.001243
1   -0.002797
Name: 380, dtype: float64
0   -0.000942
1    0.000701
Name: 410, dtype: float64
0    0.002119
1    0.001043
Name: 420, dtype: float64
0    0.002778
1   -0.000123
Name: 432, dtype: float64
0   -0.001779
1    0.000803
Name: 434, dtype: float64
0   -0.005352
1   -0.017070
Name: 435, dtype: float64
0    0.000332
1    0.000247
Name: 457, dtype: float64
0   -0.000112
1   -0.000280
Name: 480, dtype: float64
0    0.001303
1    0.000951
Name: 500, dtype: float64
0   -0.000806
1   -0.002403
Name: 586, dtype: float64
0    0.000619
1   -0.001156
Name: 587, dtype: float64
0    0.000047
1   -0.000135
Name: 588, dtype: float64
0    0.000270
1    0.000119
Name: 589, dtype: float64
0   -0.000155
1   -0.000422
Name: 590, dtype: float64
0   -0.000781
1   -0.000084
Name: 592, dtype: float64
0   -0.002750
1   -0.002622
Name: 593, dtype: float64
0   -0.000276
1    0.002705
Name: 597, dtype: float64
0    0.001654
1    0.001297
Name: 1, dtype: float64
0    0.008223
1    0.000216
Name: 7, dtype: float64
0   -0.004612
1   -0.006013
Name: 32, dtype: float64
0    0.000549
1    0.001634
Name: 62, dtype: float64
0    0.001636
1   -0.000249
Name: 65, dtype: float64
0    0.000756
1    0.000619
Name: 95, dtype: float64
0    0.000100
1    0.001389
Name: 104, dtype: float64
0   -0.000165
1   -0.000440
Name: 135, dtype: float64
0   -0.001274
1   -0.001493
Name: 141, dtype: float64
0    0.001155
1    0.000194
Name: 260, dtype: float64
0   -0.002878
1   -0.001598
Name: 637, dtype: float64
0    0.000247
1    0.001362
Name: 648, dtype: float64
0   -0.000380
1   -0.000272
Name: 653, dtype: float64
0    0.00049
1   -0.00151
Name: 661, dtype: float64
0    0.001156
1   -0.000922
Name: 711, dtype: float64
0    0.002867
1   -0.001803
Name: 719, dtype: float64
0    0.001907
1    0.000294
Name: 733, dtype: float64
0   -0.000144
1    0.000015
Name: 736, dtype: float64
0   -0.001258
1    0.000817
Name: 743, dtype: float64
0   -0.001461
1    0.004788
Name: 761, dtype: float64
0   -0.000562
1    0.000116
Name: 780, dtype: float64
0    0.003794
1   -0.002851
Name: 784, dtype: float64
0   -0.000241
1   -0.001245
Name: 786, dtype: float64
0    0.002749
1    0.003853
Name: 788, dtype: float64
0   -0.002426
1   -0.001750
Name: 1073, dtype: float64
0   -0.001413
1   -0.003765
Name: 135, dtype: float64
0   -0.006090
1    0.004017
Name: 165, dtype: float64
0   -0.007489
1   -0.000671
Name: 213, dtype: float64
0   -0.002261
1   -0.001726
Name: 231, dtype: float64
0    0.000298
1   -0.002772
Name: 267, dtype: float64
0   -0.000424
1    0.000444
Name: 344, dtype: float64
0   -0.000798
1   -0.000598
Name: 356, dtype: float64
0   -0.000515
1   -0.002288
Name: 364, dtype: float64
0    0.001711
1   -0.001313
Name: 377, dtype: float64
0   -0.001622
1    0.003650
Name: 380, dtype: float64
0    0.000402
1   -0.001153
Name: 588, dtype: float64
0    0.001487
1    0.001150
Name: 595, dtype: float64
0    0.003756
1    0.002085
Name: 637, dtype: float64
0   -0.000896
1   -0.000435
Name: 1036, dtype: float64
0   -0.000194
1   -0.001499
Name: 1253, dtype: float64
0   -0.001000
1    0.003511
Name: 1265, dtype: float64
0   -0.003539
1   -0.001101
Name: 1270, dtype: float64
0   -0.00344
1    0.00097
Name: 1347, dtype: float64
0   -0.004307
1    0.003168
Name: 1387, dtype: float64
0    0.000299
1    0.002519
Name: 1388, dtype: float64
0   -0.002479
1   -0.001390
Name: 1580, dtype: float64
0    0.002474
1   -0.002074
Name: 1702, dtype: float64
0   -0.004646
1    0.005449
Name: 1731, dtype: float64
0   -0.000147
1    0.000920
Name: 1917, dtype: float64
0   -0.003034
1    0.002300
Name: 2378, dtype: float64
0   -0.001444
1    0.000464
Name: 2379, dtype: float64
0    0.001289
1   -0.002400
Name: 2380, dtype: float64
0    0.002132
1    0.003622
Name: 2381, dtype: float64
0   -0.000855
1    0.002754
Name: 2382, dtype: float64
0    0.001394
1    0.002835
Name: 2421, dtype: float64
0   -0.000320
1   -0.000931
Name: 2463, dtype: float64
0    0.000834
1   -0.000934
Name: 2571, dtype: float64
0    0.001548
1    0.003266
Name: 2762, dtype: float64
0   -0.001601
1    0.000129
Name: 2791, dtype: float64
0    0.003290
1   -0.000535
Name: 2792, dtype: float64
0   -0.006558
1    0.000699
Name: 2858, dtype: float64
0   -0.002064
1   -0.000534
Name: 2959, dtype: float64
0    0.001144
1    0.002670
Name: 3258, dtype: float64
0    0.001142
1   -0.002332
Name: 3301, dtype: float64
0   -0.002542
1   -0.002094
Name: 3785, dtype: float64
0    0.003894
1   -0.000006
Name: 3825, dtype: float64
0    0.000864
1    0.000994
Name: 4226, dtype: float64
0   -0.006039
1    0.002461
Name: 4388, dtype: float64
0   -0.001125
1   -0.001882
Name: 4526, dtype: float64
0    0.000018
1    0.000119
Name: 4545, dtype: float64
0   -0.003388
1    0.003481
Name: 4886, dtype: float64
0   -0.001024
1   -0.002985
Name: 4994, dtype: float64
0    0.006163
1   -0.000578
Name: 5225, dtype: float64
0    0.012173
1    0.006220
Name: 5481, dtype: float64
0   -0.001908
1    0.001326
Name: 5989, dtype: float64
0    0.000544
1   -0.003702
Name: 6287, dtype: float64
0    0.001701
1    0.000124
Name: 6373, dtype: float64
0    0.000240
1   -0.000587
Name: 6377, dtype: float64
0    0.000138
1    0.000780
Name: 6482, dtype: float64
0   -0.004134
1    0.001331
Name: 7361, dtype: float64
0   -0.001430
1    0.003685
Name: 33794, dtype: float64
0    0.007598
1    0.006012
Name: 35836, dtype: float64
0   -0.003588
1    0.003099
Name: 48385, dtype: float64
0   -0.00064
1   -0.00238
Name: 50872, dtype: float64
0   -0.001394
1    0.002087
Name: 51255, dtype: float64
0    0.011184
1    0.004517
Name: 59900, dtype: float64
0   -0.003122
1    0.004302
Name: 60069, dtype: float64
0   -0.002444
1   -0.002477
Name: 60408, dtype: float64
0   -0.001660
1    0.001592
Name: 63082, dtype: float64
0    0.000553
1   -0.000150
Name: 68157, dtype: float64
0    0.000629
1   -0.000038
Name: 70286, dtype: float64
0    0.001906
1    0.001106
Name: 72998, dtype: float64
0   -0.000760
1    0.001349
Name: 73881, dtype: float64
0   -0.005002
1   -0.000989
Name: 83134, dtype: float64
0   -0.000647
1   -0.000800
Name: 86882, dtype: float64
0    0.000227
1   -0.000664
Name: 88163, dtype: float64
0   -0.001143
1    0.010943
Name: 89904, dtype: float64
0   -0.000150
1   -0.000006
Name: 92259, dtype: float64
0   -0.000983
1    0.006860
Name: 94959, dtype: float64
0    0.000022
1   -0.000080
Name: 99114, dtype: float64
0   -0.000901
1   -0.002201
Name: 101765, dtype: float64
0    0.002249
1    0.002615
Name: 47, dtype: float64
0   -0.004255
1    0.001640
Name: 305, dtype: float64

0   -0.000128
1    0.001257
Name: 597, dtype: float64
0   -0.001318
1   -0.000501
Name: 1173, dtype: float64
0    0.001410
1    0.000984
Name: 1198, dtype: float64
0   -0.000141
1   -0.000006
Name: 1590, dtype: float64
0    0.000602
1   -0.000918
Name: 1619, dtype: float64
0   -0.000175
1    0.000012
Name: 1639, dtype: float64
0   -0.000112
1   -0.000352
Name: 1721, dtype: float64
0    0.002158
1    0.000539
Name: 2145, dtype: float64
0    0.001135
1   -0.000218
Name: 2174, dtype: float64
0   -0.000178
1   -0.006849
Name: 2541, dtype: float64
0    0.000834
1   -0.000934
Name: 2571, dtype: float64
0    0.000384
1   -0.000362
Name: 3300, dtype: float64
0    0.00408
1   -0.00497
Name: 3409, dtype: float64
0   -0.000669
1    0.000498
Name: 3513, dtype: float64
0    0.004003
1    0.003673
Name: 3578, dtype: float64
0   -0.000281
1    0.000018
Name: 3624, dtype: float64
0    0.003341
1   -0.001119
Name: 3717, dtype: float64
0    0.000030
1   -0.000097
Name: 3753, dtype: float64
0   -0.000268
1    0.000228
Name: 3793, dtype: float64
0   -0.000114
1    0.000501
Name: 3798, dtype: float64
0    0.000162
1   -0.000225
Name: 3827, dtype: float64
0   -0.000103
1   -0.000234
Name: 3863, dtype: float64
0    0.000119
1    0.000118
Name: 3893, dtype: float64
0    0.000446
1    0.000142
Name: 3897, dtype: float64
0    0.000749
1   -0.000013
Name: 3952, dtype: float64
0    0.000582
1    0.002088
Name: 3977, dtype: float64
0    0.002898
1    0.003631
Name: 3996, dtype: float64
0   -0.000205
1   -0.000439
Name: 4011, dtype: float64
0    0.000351
1   -0.000196
Name: 4148, dtype: float64
0    0.000696
1    0.000556
Name: 1, dtype: float64
0   -0.000055
1    0.000312
Name: 10, dtype: float64
0   -0.001900
1    0.000965
Name: 44, dtype: float64
0   -0.002239
1    0.001401
Name: 170, dtype: float64
0    0.000941
1    0.000324
Name: 173, dtype: float64
0    0.000840
1   -0.000473
Name: 293, dtype: float64
0   -0.000144
1   -0.000264
Name: 296, dtype: float64
0   -0.000262
1    0.000084
Name: 315, dtype: float64
0   -0.001638
1    0.000005
Name: 318, dtype: float64
0    0.000122
1    0.000088
Name: 356, dtype: float64
0   -0.000539
1   -0.002284
Name: 364, dtype: float64
0    0.000272
1   -0.000123
Name: 434, dtype: float64
0    0.000109
1   -0.000793
Name: 442, dtype: float64
0   -0.000322
1   -0.000273
Name: 1092, dtype: float64
0   -0.000414
1   -0.000129
Name: 1270, dtype: float64
0   -0.000293
1   -0.000162
Name: 1580, dtype: float64
0   -0.000144
1   -0.000158
Name: 1732, dtype: float64
0    0.000129
1   -0.000072
Name: 2167, dtype: float64
0   -0.000477
1   -0.001767
Name: 2324, dtype: float64
0   -0.000413
1   -0.000225
Name: 2329, dtype: float64
0   -0.000414
1   -0.000668
Name: 2353, dtype: float64
0    0.000092
1   -0.000108
Name: 2571, dtype: float64
0   -0.000010
1    0.000081
Name: 2683, dtype: float64
0    0.000798
1   -0.000348
Name: 2701, dtype: float64
0    0.000060
1   -0.000516
Name: 3081, dtype: float64
0    0.000652
1   -0.002748
Name: 3147, dtype: float64
0    0.001309
1   -0.002537
Name: 3275, dtype: float64
0   -0.002104
1   -0.000953
Name: 3452, dtype: float64
0    0.003988
1    0.003673
Name: 3578, dtype: float64
0   -0.000268
1    0.000228
Name: 3793, dtype: float64
0    0.000095
1   -0.000017
Name: 4015, dtype: float64
0   -0.000977
1    0.000545
Name: 4148, dtype: float64
0    0.000079
1   -0.000352
Name: 4161, dtype: float64
0    0.000206
1    0.000172
Name: 4239, dtype: float64
0   -0.000847
1   -0.000501
Name: 4299, dtype: float64
0   -0.000365
1    0.000316
Name: 4306, dtype: float64
0   -0.000214
1    0.000014
Name: 4344, dtype: float64
0   -0.000142
1   -0.000023
Name: 4367, dtype: float64
0   -0.002100
1   -0.002635
Name: 4369, dtype: float64
0   -0.000190
1   -0.000257
Name: 4370, dtype: float64
0   -0.000946
1    0.000871
Name: 4387, dtype: float64
0    0.000569
1    0.000415
Name: 4446, dtype: float64
0    0.000172
1    0.000015
Name: 4643, dtype: float64
0   -0.000122
1   -0.000078
Name: 4718, dtype: float64
0    0.000186
1    0.000094
Name: 4776, dtype: float64
0   -0.001923
1    0.001947
Name: 4886, dtype: float64
0   -0.001216
1   -0.002637
Name: 4963, dtype: float64
0    0.000537
1   -0.002705
Name: 4993, dtype: float64
0    0.001133
1   -0.000996
Name: 4995, dtype: float64
0   -0.000378
1    0.000418
Name: 5010, dtype: float64
0    0.001246
1   -0.000798
Name: 5064, dtype: float64
0   -0.000438
1    0.000198
Name: 5218, dtype: float64
0    0.000081
1   -0.000634
Name: 5418, dtype: float64
0   -0.00031
1   -0.00020
Name: 5574, dtype: float64
0   -0.002426
1    0.003824
Name: 5810, dtype: float64
0   -0.003449
1   -0.000736
Name: 5952, dtype: float64
0   -0.001074
1    0.000745
Name: 5989, dtype: float64
0   -0.001560
1   -0.000397
Name: 5995, dtype: float64
0   -0.000169
1   -0.000308
Name: 6365, dtype: float64
0    0.000027
1   -0.000067
Name: 6377, dtype: float64
0   -0.000411
1    0.000156
Name: 6378, dtype: float64
0    0.000108
1   -0.000311
Name: 6539, dtype: float64
0   -0.001116
1   -0.000229
Name: 6934, dtype: float64
0    0.001748
1    0.005226
Name: 7153, dtype: float64
0    0.000513
1    0.000867
Name: 7454, dtype: float64
0   -0.000583
1   -0.001142
Name: 7458, dtype: float64
0   -0.000125
1    0.001536
Name: 8464, dtype: float64
0   -0.000648
1    0.000950
Name: 8622, dtype: float64
0    0.000345
1   -0.000057
Name: 8644, dtype: float64
0    0.000014
1    0.000508
Name: 8961, dtype: float64
0   -0.002973
1    0.000296
Name: 30707, dtype: float64
0   -0.000323
1   -0.000126
Name: 31410, dtype: float64
0    0.000406
1    0.000006
Name: 31685, dtype: float64
0    0.000338
1    0.000295
Name: 32587, dtype: float64
0    0.000134
1    0.000090
Name: 33615, dtype: float64
0    0.000084
1    0.000128
Name: 33660, dtype: float64
0    0.000465
1   -0.001201
Name: 33794, dtype: float64
0   -0.000296
1   -0.000240
Name: 35836, dtype: float64
0   -0.000218
1   -0.000062
Name: 40278, dtype: float64
0    0.000086
1   -0.000101
Name: 44022, dtype: float64
0   -0.000870
1    0.001249
Name: 44191, dtype: float64
0    0.000043
1   -0.000175
Name: 45517, dtype: float64
0    0.000132
1   -0.000317
Name: 46337, dtype: float64
0   -0.000334
1    0.000273
Name: 46723, dtype: float64
0   -0.000073
1    0.000096
Name: 47099, dtype: float64
0    0.000015
1    0.000072
Name: 48516, dtype: float64
0   -0.000052
1    0.000009
Name: 48774, dtype: float64
0    0.001464
1   -0.001419
Name: 49272, dtype: float64
0   -0.000076
1   -0.000277
Name: 50872, dtype: float64
0   -0.000019
1    0.000028
Name: 51077, dtype: float64
0   -0.000512
1    0.004716
Name: 51662, dtype: float64
0   -0.000905
1    0.000402
Name: 52722, dtype: float64
0   -0.000272
1    0.000967
Name: 54272, dtype: float64
0   -0.000190
1   -0.001012
Name: 54286, dtype: float64
0   -0.000153
1    0.000455
Name: 55247, dtype: float64
0   -0.001085
1   -0.000674
Name: 56174, dtype: float64
0    0.000230
1    0.000026
Name: 58559, dtype: float64
0    0.000083
1   -0.000329
Name: 59369, dtype: float64
0    0.000456
1   -0.000077
Name: 59784, dtype: float64
0   -0.000366
1    0.000504
Name: 60069, dtype: float64
0   -0.000201
1   -0.000855
Name: 60072, dtype: float64
0    0.000116
1   -0.000535
Name: 60074, dtype: float64
0    0.000142
1    0.001123
Name: 61323, dtype: float64
0   -0.001683
1    0.001598
Name: 63082, dtype: float64
0    0.000082
1   -0.000389
Name: 63113, dtype: float64
0   -0.003699
1   -0.001763
Name: 64614, dtype: float64
0    0.001076
1    0.001398
Name: 64839, dtype: float64
0   -0.001067
1   -0.002235
Name: 66097, dtype: float64
0   -0.001081
1   -0.001316
Name: 66511, dtype: float64
0   -0.001896
1    0.000542
Name: 67255, dtype: float64
0    0.000553
1   -0.000150
Name: 68157, dtype: float64
0   -0.000194
1    0.000044
Name: 68319, dtype: float64
0    0.001593
1    0.001656
Name: 68954, dtype: float64
0    0.002670
1    0.000159
Name: 69122, dtype: float64
0    0.000342
1   -0.000017
Name: 70286, dtype: float64
0    0.001884
1    0.001112
Name: 72998, dtype: float64
0   -0.000840
1   -0.000091
Name: 73017, dtype: float64
0   -0.001760
1    0.000373
Name: 73321, dtype: float64
0   -0.000130
1    0.000206
Name: 74458, dtype: float64
0   -0.000098
1    0.000174
Name: 76093, dtype: float64
0    0.000592
1    0.000364
Name: 78469, dtype: float64
0    0.000427
1    0.000390
Name: 78499, dtype: float64
0   -0.000851
1    0.000229

Name: 79091, dtype: float64
0    0.000064
1    0.000125
Name: 79132, dtype: float64
0   -0.004289
1    0.003564
Name: 80463, dtype: float64
0   -0.001687
1    0.001269
Name: 81229, dtype: float64
0   -0.000115
1    0.000010
Name: 81845, dtype: float64
0    0.000814
1    0.000158
Name: 82459, dtype: float64
0   -0.000087
1    0.000015
Name: 84392, dtype: float64
0   -0.000204
1   -0.001402
Name: 85020, dtype: float64
0    0.000211
1    0.000256
Name: 86882, dtype: float64
0    0.000660
1    0.001892
Name: 86911, dtype: float64
0   -0.000047
1   -0.000110
Name: 87232, dtype: float64
0   -0.000750
1    0.000048
Name: 87869, dtype: float64
0    0.000227
1   -0.000664
Name: 88163, dtype: float64
0   -0.000624
1   -0.000746
Name: 88744, dtype: float64
0   -0.001183
1    0.002004
Name: 89087, dtype: float64
0   -0.001181
1    0.001413
Name: 91529, dtype: float64
0   -0.000051
1   -0.000481
Name: 91542, dtype: float64
0   -0.001418
1   -0.001394
Name: 91658, dtype: float64
0   -0.000092
1    0.000001
Name: 92259, dtype: float64
0   -0.000016
1    0.000215
Name: 95105, dtype: float64
0   -0.000528
1    0.000416
Name: 95441, dtype: float64
0    0.000688
1   -0.000897
Name: 96079, dtype: float64
0    0.000595
1   -0.000282
Name: 96861, dtype: float64
0    0.000026
1   -0.000171
Name: 99112, dtype: float64
0    0.000022
1   -0.000080
Name: 99114, dtype: float64
0   -0.000071
1   -0.000209
Name: 101142, dtype: float64
0   -0.000339
1    0.000054
Name: 102481, dtype: float64
0   -0.001502
1   -0.001571
Name: 102903, dtype: float64
0    0.000727
1   -0.002207
Name: 103141, dtype: float64
0   -0.000529
1   -0.000245
Name: 103335, dtype: float64
0   -0.001138
1   -0.004270
Name: 103984, dtype: float64
0    0.000111
1   -0.000682
Name: 104841, dtype: float64
0   -0.001574
1   -0.000608
Name: 104913, dtype: float64
0   -0.007040
1    0.000299
Name: 105504, dtype: float64
0    0.000175
1   -0.000221
Name: 105844, dtype: float64
0   -0.000233
1   -0.001388
Name: 106491, dtype: float64
0    0.000790
1   -0.001954
Name: 106782, dtype: float64
0    0.001769
1    0.001352
Name: 106918, dtype: float64
0   -0.004962
1   -0.001040
Name: 106920, dtype: float64
0   -0.000218
1    0.000141
Name: 108689, dtype: float64
0    0.000341
1   -0.000544
Name: 108932, dtype: float64
0    0.00033
1    0.00068
Name: 109374, dtype: float64
0   -0.003145
1    0.001896
Name: 109846, dtype: float64
0   -0.000261
1    0.000128
Name: 110718, dtype: float64
0    0.000111
1   -0.000196
Name: 110730, dtype: float64
0   -0.000360
1    0.000031
Name: 111781, dtype: float64
0   -0.002210
1   -0.002201
Name: 112183, dtype: float64
0    0.001255
1    0.001100
Name: 112552, dtype: float64
0    0.000506
1    0.000874
Name: 112868, dtype: float64
0    0.000352
1    0.000466
Name: 114184, dtype: float64
0    0.000461
1    0.004553
Name: 114662, dtype: float64
0   -0.000054
1    0.000153
Name: 114795, dtype: float64
0    0.000994
1   -0.000422
Name: 115149, dtype: float64
0   -0.001094
1    0.000444
Name: 115617, dtype: float64
0    0.000317
1   -0.000019
Name: 115713, dtype: float64
0   -0.002257
1    0.006109
Name: 116797, dtype: float64
0    0.000129
1   -0.000294
Name: 116823, dtype: float64
0    0.000225
1    0.000413
Name: 117176, dtype: float64
0    0.000144
1    0.000460
Name: 117533, dtype: float64
0    0.000298
1   -0.000244
Name: 117887, dtype: float64
0    0.000020
1    0.000565
Name: 119145, dtype: float64
0   -0.000745
1    0.000392
Name: 120635, dtype: float64
0   -0.000012
1    0.000093
Name: 122882, dtype: float64
0    0.000039
1   -0.000580
Name: 122904, dtype: float64
0    0.000149
1    0.000135
Name: 127184, dtype: float64
0   -0.002558
1    0.001109
Name: 128488, dtype: float64
0   -0.000875
1   -0.000675
Name: 128620, dtype: float64
0   -0.000108
1   -0.000125
Name: 129354, dtype: float64
0    0.000029
1   -0.001081
Name: 130520, dtype: float64
0    0.000183
1   -0.000203
Name: 130578, dtype: float64
0    0.000830
1   -0.001236
Name: 131023, dtype: float64
0    0.000174
1   -0.000120
Name: 131714, dtype: float64
0   -0.002233
1   -0.000649
Name: 132157, dtype: float64
0    0.000163
1    0.000175
Name: 134853, dtype: float64
0   -0.001530
1    0.001246
Name: 135532, dtype: float64
0    0.000303
1    0.001653
Name: 135861, dtype: float64
0   -0.000104
1   -0.000075
Name: 135887, dtype: float64
0    0.000076
1    0.000340
Name: 136562, dtype: float64
0   -0.007042
1    0.002288
Name: 136598, dtype: float64
0   -0.000632
1   -0.000138
Name: 136666, dtype: float64
0    0.000394
1    0.000475
Name: 138036, dtype: float64
0   -0.002121
1    0.001658
Name: 138210, dtype: float64
0   -0.000127
1   -0.000127
Name: 139385, dtype: float64
0   -0.000098
1    0.000375
Name: 139642, dtype: float64
0   -0.001718
1   -0.009219
Name: 140711, dtype: float64
0   -0.001116
1   -0.000352
Name: 141004, dtype: float64
0   -0.000212
1   -0.000508
Name: 142488, dtype: float64
0   -0.000219
1    0.002678
Name: 148626, dtype: float64
0    0.000720
1   -0.001809
Name: 157699, dtype: float64
0   -0.001338
1   -0.000779
Name: 162350, dtype: float64
0   -0.000271
1   -0.002268
Name: 165551, dtype: float64
0   -0.000396
1    0.000304
Name: 166461, dtype: float64
0   -0.000300
1   -0.000391
Name: 168252, dtype: float64
0   -0.002144
1   -0.001711
Name: 1, dtype: float64
0   -0.000474
1    0.002674
Name: 10, dtype: float64
0    0.002498
1   -0.001645
Name: 19, dtype: float64
0    0.000279
1    0.000283
Name: 22, dtype: float64
0   -0.001617
1    0.000343
Name: 34, dtype: float64
0    0.003546
1   -0.002082
Name: 39, dtype: float64
0    0.002276
1    0.002629
Name: 47, dtype: float64
0    0.003985
1    0.000836
Name: 48, dtype: float64
0    0.001735
1   -0.002167
Name: 60, dtype: float64
0   -0.000710
1    0.000645
Name: 110, dtype: float64
0   -0.001364
1   -0.002682
Name: 150, dtype: float64
0   -0.001426
1   -0.001966
Name: 153, dtype: float64
0    0.004496
1   -0.003145
Name: 158, dtype: float64
0   -0.001604
1    0.000949
Name: 160, dtype: float64
0   -0.001010
1   -0.006621
Name: 161, dtype: float64
0   -0.006090
1    0.004008
Name: 165, dtype: float64
0   -0.000143
1   -0.000049
Name: 173, dtype: float64
0    0.002587
1   -0.001797
Name: 185, dtype: float64
0   -0.002228
1    0.000025
Name: 186, dtype: float64
0   -0.000443
1   -0.011659
Name: 193, dtype: float64
0   -0.000278
1   -0.000132
Name: 196, dtype: float64
0   -0.001526
1    0.000015
Name: 203, dtype: float64
0    0.000214
1   -0.000113
Name: 204, dtype: float64
0   -0.000123
1   -0.000095
Name: 208, dtype: float64
0    0.000130
1    0.000407
Name: 218, dtype: float64
0    0.001561
1   -0.002363
Name: 225, dtype: float64
0    0.000212
1   -0.000274
Name: 227, dtype: float64
0    0.003770
1    0.002764
Name: 231, dtype: float64
0    0.007556
1   -0.002728
Name: 234, dtype: float64
0    0.000272
1   -0.000079
Name: 236, dtype: float64
0   -0.001838
1   -0.000525
Name: 237, dtype: float64
0   -0.000367
1   -0.000277
Name: 252, dtype: float64
0   -0.001696
1   -0.004545
Name: 253, dtype: float64
0    0.000316
1   -0.000057
Name: 256, dtype: float64
0    0.002210
1   -0.003016
Name: 257, dtype: float64
0    0.002751
1    0.000094
Name: 261, dtype: float64
0    0.000477
1    0.001363
Name: 276, dtype: float64
0    0.000930
1    0.001974
Name: 282, dtype: float64
0    0.001146
1    0.007617
Name: 288, dtype: float64
0   -0.002252
1    0.000878
Name: 292, dtype: float64
0   -0.000644
1    0.000363
Name: 293, dtype: float64
0    0.000943
1    0.001734
Name: 296, dtype: float64
0    0.000105
1    0.000127
Name: 300, dtype: float64
0   -0.002242
1    0.000721
Name: 315, dtype: float64
0    0.000844
1    0.001036
Name: 316, dtype: float64
0    0.000248
1   -0.000108
Name: 317, dtype: float64
0    0.000376
1   -0.000118
Name: 329, dtype: float64
0   -0.002192
1   -0.002070
Name: 337, dtype: float64
0    0.000542
1    0.000141
Name: 338, dtype: float64
0    0.000005
1    0.000174
Name: 339, dtype: float64
0    0.009290
1   -0.009777
Name: 344, dtype: float64
0    0.004034
1   -0.003699
Name: 349, dtype: float64
0    0.000070
1   -0.002902
Name: 350, dtype: float64
0    0.001046
1    0.000757
Name: 356, dtype: float64
0   -0.000539
1   -0.002284
Name: 364, dtype: float64
0    0.004558
1   -0.003336
Name: 367, dtype: float64
0    0.001701
1   -0.001298
Name: 377, dtype: float64
0   -0.001618
1    0.003655
Name: 380, dtype: float64
0   -0.000941
1    0.000682
Name: 410, dtype: float64
0   -0.000323
1   -0.000158
Name: 420, dtype: float64
0    0.002332
1   -0.001052

Name: 434, dtype: float64
0   -0.001624
1   -0.005206
Name: 435, dtype: float64
0    0.000192
1   -0.003819
Name: 440, dtype: float64
0    0.000930
1   -0.006791
Name: 442, dtype: float64
0   -0.001318
1    0.001683
Name: 454, dtype: float64
0    0.000333
1    0.000245
Name: 457, dtype: float64
0    0.000854
1   -0.002626
Name: 474, dtype: float64
0    0.000107
1    0.000021
Name: 477, dtype: float64
0   -0.000957
1   -0.002413
Name: 480, dtype: float64
0   -0.001702
1   -0.001220
Name: 500, dtype: float64
0    0.001727
1   -0.004369
Name: 508, dtype: float64
0    0.002066
1   -0.004938
Name: 539, dtype: float64
0    0.000202
1   -0.001965
Name: 585, dtype: float64
0    0.000122
1    0.000368
Name: 586, dtype: float64
0   -0.000797
1    0.001504
Name: 587, dtype: float64
0    0.000046
1   -0.000134
Name: 588, dtype: float64
0    0.002320
1    0.000989
Name: 589, dtype: float64
0   -0.001314
1   -0.003644
Name: 590, dtype: float64
0   -0.000764
1   -0.000104
Name: 592, dtype: float64
0    0.000420
1    0.000401
Name: 593, dtype: float64
0    0.001491
1    0.001134
Name: 595, dtype: float64
0   -0.000124
1    0.001230
Name: 597, dtype: float64
0   -0.001222
1    0.000110
Name: 736, dtype: float64
0    0.002705
1   -0.001693
Name: 170, dtype: float64
0    0.000054
1    0.000298
Name: 247, dtype: float64
0   -0.000882
1   -0.000135
Name: 260, dtype: float64
0   -0.000144
1   -0.000264
Name: 296, dtype: float64
0    0.002247
1   -0.000007
Name: 318, dtype: float64
0   -0.002515
1   -0.003278
Name: 319, dtype: float64
0   -0.000438
1    0.000282
Name: 327, dtype: float64
0   -0.001264
1   -0.000915
Name: 356, dtype: float64
0    0.001148
1   -0.000827
Name: 509, dtype: float64
0   -0.000267
1   -0.000336
Name: 527, dtype: float64
0    0.002324
1    0.002823
Name: 531, dtype: float64
0   -0.000564
1   -0.000212
Name: 608, dtype: float64
0    0.002226
1    0.000088
Name: 750, dtype: float64
0    0.003809
1    0.007489
Name: 830, dtype: float64
0   -0.000176
1   -0.004434
Name: 1196, dtype: float64
0   -0.000073
1   -0.000232
Name: 1199, dtype: float64
0    0.000062
1    0.000222
Name: 1206, dtype: float64
0    0.000157
1    0.000350
Name: 1219, dtype: float64
0   -0.000009
1   -0.000761
Name: 1296, dtype: float64
0    0.004133
1    0.002294
Name: 1580, dtype: float64
0    0.002957
1    0.008985
Name: 1721, dtype: float64
0   -0.002001
1    0.002335
Name: 2571, dtype: float64
0    0.003588
1    0.001115
Name: 2716, dtype: float64
0   -0.001831
1   -0.003976
Name: 2762, dtype: float64
0    0.002136
1   -0.000236
Name: 2858, dtype: float64
0   -0.000242
1   -0.000061
Name: 2959, dtype: float64
0   -0.003557
1   -0.002813
Name: 2997, dtype: float64
0    0.004010
1   -0.000252
Name: 3624, dtype: float64
0    0.000157
1   -0.000013
Name: 3677, dtype: float64
0    0.009288
1   -0.008036
Name: 4306, dtype: float64
0   -0.004016
1   -0.007994
Name: 4361, dtype: float64
0    0.000068
1    0.000264
Name: 4848, dtype: float64
0    0.010243
1   -0.010371
Name: 4886, dtype: float64
0    0.000337
1   -0.000079
Name: 4967, dtype: float64
0    0.000216
1   -0.000226
Name: 4973, dtype: float64
0   -0.000867
1   -0.000020
Name: 4979, dtype: float64
0   -0.001369
1    0.001203
Name: 4995, dtype: float64
0    0.000057
1   -0.000632
Name: 5303, dtype: float64
0   -0.000410
1   -0.004686
Name: 5445, dtype: float64
0   -0.000842
1    0.001443
Name: 5617, dtype: float64
0   -0.000010
1    0.000167
Name: 5902, dtype: float64
0    0.000878
1    0.000047
Name: 5951, dtype: float64
0    0.007461
1    0.001591
Name: 5952, dtype: float64
0    0.004291
1    0.007834
Name: 6365, dtype: float64
0   -0.001526
1    0.004393
Name: 6539, dtype: float64
0   -0.000322
1    0.000232
Name: 6874, dtype: float64
0   -0.001194
1    0.000407
Name: 7323, dtype: float64
0    0.006553
1    0.000883
Name: 8360, dtype: float64
0   -0.000032
1    0.000555
Name: 8959, dtype: float64
0    0.003542
1   -0.002747
Name: 26810, dtype: float64
0   -0.000354
1   -0.002420
Name: 46976, dtype: float64
0   -0.002144
1   -0.001711
Name: 1, dtype: float64
0   -0.000274
1    0.000130
Name: 2, dtype: float64
0   -0.000584
1   -0.000014
Name: 7, dtype: float64
0   -0.000055
1    0.000312
Name: 10, dtype: float64
0    0.001172
1   -0.000567
Name: 11, dtype: float64
0   -0.000056
1   -0.000131
Name: 13, dtype: float64
0    0.001731
1    0.000341
Name: 17, dtype: float64
0    0.000055
1    0.000159
Name: 21, dtype: float64
0   -0.000539
1   -0.000705
Name: 32, dtype: float64
0    0.002060
1    0.000113
Name: 36, dtype: float64
0    0.001341
1   -0.000279
Name: 46, dtype: float64
0    0.000147
1    0.000256
Name: 58, dtype: float64
0   -0.004394
1    0.005488
Name: 60, dtype: float64
0   -0.000713
1   -0.002137
Name: 62, dtype: float64
0    0.000539
1    0.000782
Name: 73, dtype: float64
0   -0.000013
1   -0.000352
Name: 81, dtype: float64
0    0.002634
1   -0.002176
Name: 86, dtype: float64
0   -0.003294
1   -0.000991
Name: 105, dtype: float64
0   -0.000710
1    0.000645
Name: 110, dtype: float64
0    0.004803
1   -0.001326
Name: 112, dtype: float64
0   -0.000166
1   -0.000439
Name: 135, dtype: float64
0   -0.001270
1   -0.001503
Name: 141, dtype: float64
0   -0.001364
1   -0.002682
Name: 150, dtype: float64
0   -0.000077
1   -0.000191
Name: 151, dtype: float64
0   -0.001426
1   -0.001966
Name: 153, dtype: float64
0   -0.000712
1    0.000468
Name: 165, dtype: float64
0    0.000660
1   -0.000181
Name: 168, dtype: float64
0   -0.002672
1   -0.000067
Name: 172, dtype: float64
0    0.000941
1    0.000324
Name: 173, dtype: float64
0    0.000302
1   -0.000210
Name: 185, dtype: float64
0   -0.000123
1   -0.000095
Name: 208, dtype: float64
0   -0.000523
1   -0.000863
Name: 222, dtype: float64
0   -0.003614
1   -0.000427
Name: 224, dtype: float64
0   -0.000367
1   -0.000277
Name: 252, dtype: float64
0   -0.000244
1    0.000012
Name: 258, dtype: float64
0    0.001151
1    0.000177
Name: 260, dtype: float64
0    0.000321
1    0.000011
Name: 261, dtype: float64
0    0.000416
1    0.000200
Name: 266, dtype: float64
0    0.001146
1    0.007617
Name: 288, dtype: float64
0    0.000098
1   -0.000055
Name: 293, dtype: float64
0   -0.001231
1   -0.002263
Name: 296, dtype: float64
0   -0.002979
1    0.000181
Name: 303, dtype: float64
0    0.000009
1    0.000216
Name: 314, dtype: float64
0   -0.000343
1    0.000001
Name: 318, dtype: float64
0    0.000376
1   -0.000118
Name: 329, dtype: float64
0    0.000542
1    0.000141
Name: 338, dtype: float64
0    0.000471
1   -0.000432
Name: 349, dtype: float64
0    0.001046
1    0.000757
Name: 356, dtype: float64
0    0.004454
1    0.001410
Name: 357, dtype: float64
0    0.000889
1    0.003768
Name: 364, dtype: float64
0   -0.000056
1   -0.000005
Name: 368, dtype: float64
0   -0.001304
1    0.000995
Name: 377, dtype: float64
0   -0.000189
1    0.000427
Name: 380, dtype: float64
0    0.000192
1   -0.003819
Name: 440, dtype: float64
0   -0.000713
1    0.005204
Name: 442, dtype: float64
0    0.002847
1    0.002101
Name: 457, dtype: float64
0    0.000854
1   -0.002626
Name: 474, dtype: float64
0   -0.000112
1   -0.000282
Name: 480, dtype: float64
0    0.000049
1   -0.000884
Name: 491, dtype: float64
0    0.004310
1    0.003089
Name: 500, dtype: float64
0    0.000702
1   -0.001403
Name: 524, dtype: float64
0    0.000824
1    0.001036
Name: 527, dtype: float64
0    0.000985
1    0.000162
Name: 529, dtype: float64
0    0.000241
1   -0.000577
Name: 539, dtype: float64
0    0.000360
1   -0.000326
Name: 541, dtype: float64
0   -0.000091
1   -0.000362
Name: 552, dtype: float64
0    0.000122
1    0.000368
Name: 586, dtype: float64
0    0.000046
1   -0.000134
Name: 588, dtype: float64
0    0.002320
1    0.000989
Name: 589, dtype: float64
0   -0.001314
1   -0.003644
Name: 590, dtype: float64
0    0.000420
1    0.000401
Name: 593, dtype: float64
0    0.001491
1    0.001134
Name: 595, dtype: float64
0    0.000019
1   -0.000187
Name: 597, dtype: float64
0    0.000390
1    0.000218
Name: 640, dtype: float64
0   -0.000210
1   -0.000038
Name: 647, dtype: float64
0   -0.000038
1   -0.000207
Name: 648, dtype: float64
0   -0.000380
1   -0.000272
Name: 653, dtype: float64
0    0.000081
1    0.000009
Name: 707, dtype: float64
0    0.000273
1   -0.000224
Name: 708, dtype: float64
0    0.000223
1    0.000033
Name: 733, dtype: float64
0   -0.000562
1    0.000115
Name: 780, dtype: float64
0    0.002544
1   -0.001916
Name: 784, dtype: float64
0    0.000186
1    0.000954
Name: 786, dtype: float64
0   -0.000187
1    0.000035
Name: 802, dtype: float64
0   -0.001789
1   -0.006164
Name: 809, dtype: float64
0   -0.001028
1   -0.000757
Name: 832, dtype: float64
0    0.000793
1    0.002809
Name: 836, dtype: float64
0    0.000313
1    0.000190
Name: 902, dtype: float64
0   -0.000414
1    0.000284
Name: 924, dtype: float64
0   -0.000539
1   -0.000023
Name: 944, dtype: float64
0    0.000564
1    0.001665
Name: 954, dtype: float64
0   -0.000699
1    0.001855
Name: 1007, dtype: float64
0    0.000160
1   -0.000898
Name: 1019, dtype: float64
0    0.000183
1    0.000070
Name: 1025, dtype: float64
0    0.000124
1    0.000291
Name: 1028, dtype: float64
0    0.000033
1    0.000557
Name: 1035, dtype: float64
0   -0.000106
1   -0.000050
Name: 1036, dtype: float64
0   -0.000482
1   -0.003130
Name: 1047, dtype: float64
0   -0.002547
1    0.000934
Name: 1057, dtype: float64
0    0.000059
1   -0.000322
Name: 1060, dtype: float64
0   -0.001124
1    0.000045
Name: 1064, dtype: float64
0    0.000370
1    0.000267
Name: 1073, dtype: float64
0    0.003553
1   -0.000302
Name: 1079, dtype: float64
0    0.001788
1   -0.000287
Name: 1097, dtype: float64
0   -0.001223
1    0.001966
Name: 1100, dtype: float64
0    0.00009
1   -0.00038
Name: 1101, dtype: float64
0    0.000278
1   -0.000120
Name: 1136, dtype: float64
0   -0.000656
1   -0.000742
Name: 1183, dtype: float64
0    0.000107
1    0.002688
Name: 1196, dtype: float64
0   -0.003194
1    0.001903
Name: 1197, dtype: float64
0    0.001415
1    0.000979
Name: 1198, dtype: float64
0    0.000191
1   -0.000012
Name: 1200, dtype: float64
0   -0.000116
1    0.000217
Name: 1207, dtype: float64
0    0.002918
1   -0.004295
Name: 1210, dtype: float64
0   -0.000644
1    0.000515
Name: 1214, dtype: float64
0    0.000089
1    0.000395
Name: 1220, dtype: float64
0    0.002396
1   -0.001822
Name: 1240, dtype: float64
0    0.001451
1    0.000192
Name: 1242, dtype: float64
0    0.000186
1    0.000161
Name: 1247, dtype: float64
0   -0.000597
1   -0.000793
Name: 1259, dtype: float64
0   -0.001002
1    0.003512
Name: 1265, dtype: float64
0   -0.003543
1   -0.001101
Name: 1270, dtype: float64
0    0.000020
1    0.000426

Name: 1275, dtype: float64
0    0.000808
1    0.000064
Name: 1291, dtype: float64
0   -0.000322
1    0.000126
Name: 1297, dtype: float64
0    0.000485
1   -0.000038
Name: 1302, dtype: float64
0   -0.000078
1   -0.000605
Name: 1307, dtype: float64
0    0.000214
1   -0.000202
Name: 1320, dtype: float64
0   -0.001501
1    0.000993
Name: 1356, dtype: float64
0   -0.000072
1    0.000339
Name: 1370, dtype: float64
0    0.000506
1    0.000375
Name: 1371, dtype: float64
0    0.003868
1   -0.002687
Name: 1372, dtype: float64
0   -0.000995
1    0.001333
Name: 1373, dtype: float64
0   -0.004226
1   -0.000896
Name: 1374, dtype: float64
0    0.000943
1    0.000598
Name: 1375, dtype: float64
0   -0.000965
1   -0.000678
Name: 1376, dtype: float64
0    0.003428
1   -0.008957
Name: 1377, dtype: float64
0    0.000562
1    0.000191
Name: 1380, dtype: float64
0   -0.001714
1   -0.000976
Name: 1385, dtype: float64
0   -0.000504
1    0.000371
Name: 1387, dtype: float64
0   -0.001605
1    0.001543
Name: 1391, dtype: float64
0   -0.001967
1    0.000323
Name: 1393, dtype: float64
0    0.000029
1   -0.000478
Name: 1396, dtype: float64
0    0.000195
1    0.001300
Name: 1407, dtype: float64
0   -0.001386
1   -0.000832
Name: 1408, dtype: float64
0    0.002983
1   -0.000951
Name: 1466, dtype: float64
0   -0.000133
1   -0.000203
Name: 1485, dtype: float64
0   -0.000131
1   -0.000002
Name: 1500, dtype: float64
0    0.008422
1   -0.008177
Name: 1517, dtype: float64
0   -0.000065
1   -0.000206
Name: 1527, dtype: float64
0    0.002874
1    0.000929
Name: 1544, dtype: float64
0   -0.000049
1   -0.000529
Name: 1552, dtype: float64
0    0.001541
1    0.002373
Name: 1566, dtype: float64
0    0.001022
1    0.000402
Name: 1569, dtype: float64
0    0.000020
1   -0.000019
Name: 1573, dtype: float64
0   -0.002506
1   -0.001391
Name: 1580, dtype: float64
0   -0.00250
1   -0.00306
Name: 1584, dtype: float64
0    0.002585
1    0.000488
Name: 1587, dtype: float64
0   -0.001132
1   -0.002875
Name: 1594, dtype: float64
0   -0.001066
1    0.000123
Name: 1608, dtype: float64
0   -0.002759
1    0.002576
Name: 1610, dtype: float64
0    0.000266
1   -0.000166
Name: 1616, dtype: float64
0    0.000154
1    0.000548
Name: 1653, dtype: float64
0   -0.000214
1   -0.000317
Name: 1676, dtype: float64
0   -0.000198
1   -0.001201
Name: 1680, dtype: float64
0   -0.000076
1    0.000265
Name: 1682, dtype: float64
0    0.000746
1   -0.004839
Name: 1686, dtype: float64
0    0.000195
1    0.000182
Name: 1688, dtype: float64
0    0.001565
1   -0.002554
Name: 1690, dtype: float64
0   -0.000139
1    0.000048
Name: 1704, dtype: float64
0    0.001620
1    0.000374
Name: 1717, dtype: float64
0   -0.000994
1   -0.003021
Name: 1721, dtype: float64
0   -0.000335
1    0.001137
Name: 1722, dtype: float64
0    0.001179
1   -0.000167
Name: 1726, dtype: float64
0    0.002329
1    0.000862
Name: 1747, dtype: float64
0   -0.000071
1   -0.000090
Name: 1777, dtype: float64
0    0.000725
1   -0.001023
Name: 1855, dtype: float64
0    0.000067
1   -0.000550
Name: 1876, dtype: float64
0    0.000655
1    0.002992
Name: 1882, dtype: float64
0    0.000105
1    0.000375
Name: 1907, dtype: float64
0   -0.000183
1    0.000073
Name: 1909, dtype: float64
0   -0.000202
1    0.000405
Name: 2006, dtype: float64
0    0.000053
1   -0.000053
Name: 2019, dtype: float64
0   -0.001311
1   -0.002315
Name: 2028, dtype: float64
0   -0.000226
1    0.000152
Name: 2141, dtype: float64
0   -0.000015
1   -0.000702
Name: 2279, dtype: float64
0   -0.002296
1    0.000098
Name: 2294, dtype: float64
0   -0.000095
1    0.000244
Name: 2316, dtype: float64
0    0.000368
1   -0.000067
Name: 2320, dtype: float64
0    0.003380
1   -0.002672
Name: 2321, dtype: float64
0   -0.000098
1   -0.000018
Name: 2322, dtype: float64
0    0.001788
1   -0.000929
Name: 2393, dtype: float64
0   -0.000287
1   -0.000205
Name: 2396, dtype: float64
0    0.000020
1    0.000053
Name: 2424, dtype: float64
0    0.000186
1    0.000178
Name: 2431, dtype: float64
0    0.000209
1    0.000163
Name: 2433, dtype: float64
0   -0.000210
1   -0.000066
Name: 2490, dtype: float64
0    0.001111
1   -0.002465
Name: 2496, dtype: float64
0    0.002490
1   -0.001443
Name: 2501, dtype: float64
0   -0.002599
1   -0.000527
Name: 2502, dtype: float64
0   -0.000109
1   -0.000343
Name: 2549, dtype: float64
0    0.000025
1    0.000366
Name: 2567, dtype: float64
0    0.000092
1   -0.000108
Name: 2571, dtype: float64
0   -0.000291
1   -0.000291
Name: 2605, dtype: float64
0    0.000019
1    0.001305
Name: 2628, dtype: float64
0    0.000798
1   -0.000348
Name: 2701, dtype: float64
0   -0.000241
1    0.000501
Name: 2761, dtype: float64
0   -0.00250
1   -0.00543
Name: 2762, dtype: float64
0    0.010851
1   -0.001196
Name: 2858, dtype: float64
0   -0.001256
1   -0.003538
Name: 2906, dtype: float64
0    0.002726
1    0.002156
Name: 2997, dtype: float64
0    0.002371
1   -0.000946
Name: 3052, dtype: float64
0   -0.000186
1   -0.001772
Name: 3114, dtype: float64
0   -0.002768
1    0.000756
Name: 3155, dtype: float64
0    0.000331
1    0.001160
Name: 3175, dtype: float64
0    0.000007
1    0.000247
Name: 5060, dtype: float64
0   -0.001409
1   -0.001413
Name: 123, dtype: float64
0   -0.001344
1   -0.000877
Name: 232, dtype: float64
0   -0.000993
1   -0.002477
Name: 492, dtype: float64
0    0.000466
1    0.000018
Name: 750, dtype: float64
0    0.000406
1    0.000406
Name: 1077, dtype: float64
0   -0.001297
1    0.000712
Name: 1104, dtype: float64
0   -0.000725
1   -0.003115
Name: 1230, dtype: float64
0   -0.002355
1   -0.000637
Name: 1244, dtype: float64
0    0.000442
1   -0.000027
Name: 1701, dtype: float64
0   -0.001529
1    0.000766
Name: 1953, dtype: float64
0   -0.003005
1    0.001428
Name: 2359, dtype: float64
0   -0.000224
1   -0.004654
Name: 2371, dtype: float64
0    0.005690
1    0.004836
Name: 3388, dtype: float64
0   -0.000100
1    0.000196
Name: 4017, dtype: float64
0    0.000559
1    0.000427
Name: 4037, dtype: float64
0   -0.000149
1   -0.000316
Name: 5291, dtype: float64
0    0.000561
1   -0.003637
Name: 5650, dtype: float64
0   -0.000084
1   -0.000351
Name: 6016, dtype: float64
0    0.000179
1   -0.000191
Name: 6993, dtype: float64
0   -0.000321
1    0.000002
Name: 8042, dtype: float64
0   -0.000062
1    0.000277
Name: 8228, dtype: float64
0   -0.000242
1    0.000119
Name: 8645, dtype: float64
0    0.000311
1    0.000034
Name: 44555, dtype: float64
0    0.001244
1    0.000616
Name: 4, dtype: float64
0    0.003830
1    0.000092
Name: 7, dtype: float64
0    0.008257
1   -0.005437
Name: 19, dtype: float64
0   -0.000104
1    0.000160
Name: 25, dtype: float64
0   -0.000539
1   -0.000705
Name: 32, dtype: float64
0    0.001073
1   -0.000630
Name: 39, dtype: float64
0    0.002276
1    0.002629
Name: 47, dtype: float64
0    0.006485
1    0.005313
Name: 95, dtype: float64
0   -0.003294
1   -0.000991
Name: 105, dtype: float64
0   -0.000710
1    0.000645
Name: 110, dtype: float64
0   -0.000159
1   -0.000313
Name: 150, dtype: float64
0   -0.003070
1   -0.004233
Name: 153, dtype: float64
0   -0.000134
1   -0.003528
Name: 193, dtype: float64
0    0.001752
1    0.001284
Name: 231, dtype: float64
0    0.003559
1    0.001710
Name: 266, dtype: float64
0    0.000930
1    0.001974
Name: 282, dtype: float64
0   -0.000053
1   -0.000351
Name: 288, dtype: float64
0    0.000943
1    0.001734
Name: 296, dtype: float64
0    0.002247
1   -0.000007
Name: 318, dtype: float64
0    0.002860
1    0.002701
Name: 337, dtype: float64
0    0.000005
1    0.000174
Name: 339, dtype: float64
0    0.006051
1   -0.006367
Name: 344, dtype: float64
0   -0.001183
1    0.004313
Name: 351, dtype: float64
0    0.000122
1    0.000088
Name: 356, dtype: float64
0    0.015063
1   -0.011024
Name: 367, dtype: float64
0    0.000020
1    0.000131
Name: 376, dtype: float64
0   -0.001304
1    0.000995
Name: 377, dtype: float64
0   -0.000131
1   -0.000054
Name: 383, dtype: float64
0    0.000272
1   -0.000123
Name: 434, dtype: float64
0   -0.001556
1   -0.000704
Name: 448, dtype: float64
0    0.001363
1   -0.000848
Name: 455, dtype: float64
0    0.000107
1    0.000021
Name: 477, dtype: float64
0    0.000733
1    0.001849
Name: 480, dtype: float64
0   -0.000324
1    0.005800
Name: 491, dtype: float64
0   -0.001323
1    0.003348
Name: 508, dtype: float64
0    0.002056
1   -0.001481
Name: 509, dtype: float64
0   -0.000538
1    0.001075
Name: 524, dtype: float64
0   -0.000631
1   -0.000794
Name: 527, dtype: float64
0    0.000241
1   -0.000577
Name: 539, dtype: float64
0    0.000687
1   -0.001173

Name: 540, dtype: float64
0    0.000598
1    0.002375
Name: 552, dtype: float64
0   -0.000195
1   -0.000067
Name: 553, dtype: float64
0   -0.000803
1   -0.002411
Name: 586, dtype: float64
0   -0.000154
1   -0.000426
Name: 590, dtype: float64
0   -0.001645
1   -0.000225
Name: 592, dtype: float64
0    0.000420
1    0.000401
Name: 593, dtype: float64
0   -0.000124
1    0.001230
Name: 597, dtype: float64
0    0.003906
1   -0.002942
Name: 784, dtype: float64
0   -0.000274
1    0.000130
Name: 2, dtype: float64
0    0.000363
1   -0.002049
Name: 10, dtype: float64
0   -0.000898
1    0.000434
Name: 11, dtype: float64
0    0.005720
1    0.001127
Name: 17, dtype: float64
0    0.005378
1   -0.003541
Name: 19, dtype: float64
0   -0.000363
1   -0.001040
Name: 21, dtype: float64
0   -0.004612
1   -0.006037
Name: 32, dtype: float64
0    0.000247
1   -0.000052
Name: 34, dtype: float64
0    0.003546
1   -0.002082
Name: 39, dtype: float64
0   -0.006278
1    0.003188
Name: 44, dtype: float64
0   -0.003754
1   -0.004337
Name: 47, dtype: float64
0   -0.004970
1   -0.004071
Name: 95, dtype: float64
0   -0.000710
1    0.000645
Name: 110, dtype: float64
0   -0.000159
1   -0.000313
Name: 150, dtype: float64
0   -0.001426
1   -0.001966
Name: 153, dtype: float64
0    0.001229
1   -0.000728
Name: 160, dtype: float64
0   -0.000118
1   -0.000773
Name: 161, dtype: float64
0   -0.000712
1    0.000468
Name: 165, dtype: float64
0   -0.004267
1    0.002964
Name: 185, dtype: float64
0    0.001733
1    0.001340
Name: 208, dtype: float64
0   -0.001197
1    0.001811
Name: 225, dtype: float64
0    0.001752
1    0.001284
Name: 231, dtype: float64
0   -0.005606
1   -0.015021
Name: 253, dtype: float64
0   -0.002728
1   -0.001310
Name: 266, dtype: float64
0   -0.000713
1   -0.001513
Name: 282, dtype: float64
0    0.000746
1    0.004961
Name: 288, dtype: float64
0    0.001726
1   -0.000673
Name: 292, dtype: float64
0   -0.000144
1   -0.000264
Name: 296, dtype: float64
0   -0.000129
1   -0.000158
Name: 316, dtype: float64
0   -0.001629
1    0.000710
Name: 317, dtype: float64
0   -0.002933
1    0.000010
Name: 318, dtype: float64
0    0.000376
1   -0.000118
Name: 329, dtype: float64
0   -0.002192
1   -0.002070
Name: 337, dtype: float64
0    0.002811
1   -0.002958
Name: 344, dtype: float64
0   -0.000802
1   -0.000580
Name: 356, dtype: float64
0   -0.011281
1   -0.003571
Name: 357, dtype: float64
0   -0.000063
1   -0.000267
Name: 364, dtype: float64
0    0.004558
1   -0.003336
Name: 367, dtype: float64
0   -0.001304
1    0.000995
Name: 377, dtype: float64
0    0.001240
1   -0.002801
Name: 380, dtype: float64
0   -0.000941
1    0.000682
Name: 410, dtype: float64
0    0.002116
1    0.001035
Name: 420, dtype: float64
0    0.002775
1   -0.000132
Name: 432, dtype: float64
0   -0.001787
1    0.000806
Name: 434, dtype: float64
0   -0.005369
1   -0.017206
Name: 435, dtype: float64
0    0.000333
1    0.000246
Name: 457, dtype: float64
0   -0.000112
1   -0.000282
Name: 480, dtype: float64

KeyboardInterrupt:

### Question 5

What happens as you increase the number of iterations? What happens if you increase the learning rate?

#### Question 5 Answer

Write your answer to the question in this box.

In [125]:
# Question 5 Code Answer

print("the square difference gets too large")

the square difference gets too large

## Making Predictions

Predictions can be made from the model of the appropriate rating for a given user, $i$, for a given film, $j$, by simply taking the inner product between their vectors $\mathbf{u}_i$ and $\mathbf{v}_j$.

### Question 6

Create a function that provides the prediction of the ratings for the users in the dataset. Is the quality of the predictions affected by the number of iterations or the learning rate? The function should receive `Y`, `U` and `V` and return the predictions and the absolute error between the predictions and the actual rating given by the users. The predictions and the absolute error should be added as additional columns to the dataframe `Y`.

In [127]:
# Question 6 Code Answer

s = 0;
for i in range(len(Y)):
    row = Y.iloc[i]
    user = row['users']
    film = row['movies']
    rating = row['ratings']
    o = row['ratingsorig']
    prediction = np.dot(U.loc[user], V.loc[film]) # vTu

    print(prediction + mean_ratings_train, o)
#     print(abs(prediction-rating) / rating)
#     s += abs(prediction-rating) / rating
# #     if i ==10:
# #         break
# s / len(Y)

3.8677203340513318 3.5
3.8677173266487883 4.0
3.8677186669617716 3.0
3.8677183569585587 5.0
3.8677195035768492 3.0
3.867718119773249 5.0
3.867720112217529 4.0
3.8677190363556035 4.0
3.867719271963216 4.5
3.8677172634254195 4.0
3.867719669649556 5.0
3.8677178947226722 4.0
3.8677214264477118 4.0
3.867720988642994 4.0
3.8677206715062247 4.0
3.867719991421285 4.0
3.867719727852201 4.0
3.867718194001461 4.0
3.8677193610055123 5.0
3.8677211622287855 4.0
3.867717909820877 3.0
3.8677180650273857 4.0
3.867718100926148 4.0
3.8677189712025863 3.0
3.8677204561879712 4.0
3.8677193118005913 5.0
3.8677195112325564 4.5
3.8677197430884243 5.0
3.8677143781483325 5.0
3.8677185461313273 4.0
3.867718094550908 4.0
3.8677179118511136 3.5
3.867719645338374 4.0
3.8677167859068704 4.0
3.8677195274499026 4.5
3.8677179879848422 4.0
3.8677192605912074 4.0
3.8677191225780603 4.0
3.8677206122920107 5.0
3.8677178250509456 3.5
3.8677183425976143 4.5
3.86772004967183 3.5
3.86771762684256 4.0
3.8677192810515484 4.0
3.8677172160194395 4.0
3.8677176513319584 4.5
3.8677201768995424 5.0
3.867719346337738 5.0
3.867717934096969 5.0
3.8677181622762276 4.0
3.867717953358273 4.5
3.867719396054389 4.0
3.8677208864113783 4.0
3.867720618177993 4.0
3.8677196501973663 3.0
3.8677218139299905 4.5
3.8677185894994754 4.5
3.86772006247038 4.5
3.867719923062692 4.0
3.8677186202345575 4.0
3.867718532781184 4.5
3.867719024297842 4.0
3.8677195137946514 4.5
3.8677146390165054 5.0
3.867720687542432 3.5
3.8677198897594 4.5
3.867720784255213 3.5
3.8677190540367063 3.5
3.8677172138385374 4.0
3.8677161067110055 4.0
3.8677195247118323 5.0
3.8677203411587096 4.0
3.8677166767037257 4.0
3.867715683918615 4.0
3.8677174524086158 4.0
3.8677174930630946 4.0
3.867717331473556 3.5
3.8677206856516086 4.0
3.8677196168322765 4.0
3.867718493402192 3.5
3.867717925068971 4.5
3.8677190108349446 4.0
3.8677192698435325 4.0
3.867718450361325 3.5
3.86771829938974 4.0
3.8677180390528 4.0
3.8677186008835065 4.0
3.867718222617189 5.0
3.8677199836268663 4.0
3.86771853965729 3.5
3.867716019073405 5.0
3.86771778860196 3.5
3.8677176581361725 4.5
3.8677194221878906 4.5
3.867717049266714 4.0
3.8677198990122266 4.5
3.8677180872735732 4.5
3.86771952375805 4.0
3.8677168315659243 4.0
3.867717747136202 4.0
3.86771792009856 3.0
3.8677178460586754 3.5
3.867720531047782 3.5
3.867718229124851 5.0
3.8677197982697216 4.0
3.8677232209133514 4.5
3.8677223892358152 3.5
3.867716429288976 3.0
3.867719425564571 5.0
3.867718865728374 5.0
3.8677167490014854 4.0
3.8677190417630634 4.0
3.867716565504985 5.0
3.867716809648765 5.0
3.8677180435695955 4.5
3.8677167199634646 5.0
3.86771914157912 4.5
3.8677195251369527 4.5
3.867718058301985 4.0
3.867718061727149 4.0
3.867720003692925 3.5
3.8677197939898487 3.5
3.8677185117901542 5.0
3.867717595395056 4.0
3.867718481094685 5.0
3.8677186282352545 4.5
3.8677188612669324 4.0
3.8677142779257876 4.0
3.86771872101044 4.0
3.867719795986974 4.5
3.867719268572979 3.5
3.867716904062569 5.0
3.8677191053770144 4.0
3.86771893304892 4.5
3.8677204084694154 4.0
3.8677195587458493 4.5
3.867717500993202 4.5
3.8677180475768944 4.5
3.8677207681204466 4.0
3.8677196327420145 5.0
3.86771841123523 4.5
3.86771753107101 4.0
3.8677183953259164 4.5
3.8677181390776676 3.5
3.8677180624816834 5.0
3.8677190685522507 4.0
3.867718682709862 4.0
3.867719644894461 4.0
3.867719613153214 4.0
3.8677197655930726 5.0
3.867719719307082 4.5
3.8677185980893998 5.0
3.8677209843316884 5.0
3.8677176044764545 3.5
3.8677193024346397 5.0
3.8677215304533408 5.0
3.867718660501387 4.0
3.8677198085056346 4.5
3.8677194291656027 4.5
3.867715496322253 4.5
3.86772119879015 5.0
3.8677187172594714 4.0
3.8677185182541827 4.5
3.8677201089307194 3.5
3.8677187805702697 5.0
3.8677189537792107 4.0
3.867718819334665 4.0
3.8677198032057434 4.0
3.867715715653095 3.0
3.8677161835145584 4.5
3.867717056904468 4.5
3.867719802176278 3.5
3.8677156236170487 5.0
3.867717971731401 4.0
3.8677178274795754 4.5
3.8677185204054707 5.0
3.8677171631120726 4.0
3.867716159097233 5.0
3.867719175967663 4.0
3.867717884630561 5.0
3.86771577048378 4.0
3.8677182396130187 4.0
3.867715828640188 4.0
3.8677186096204914 4.5
3.867718054890935 4.0
3.867718817840505 4.5
3.867717191455471 4.0
3.86771772959628 3.0
3.867716115874831 3.5
3.8677194292827553 4.0
3.8677168425480706 3.5
3.8677185471968625 4.0
3.8677187269337696 4.5
3.867718214114957 4.0
3.8677140936549734 3.5
3.8677169571793404 4.0
3.867718511231083 4.5
3.8677199407628438 3.0
3.867719188549663 4.0
3.8677191798862323 3.5
3.8677205009901807 5.0
3.8677173417463613 3.5
3.8677175253080494 4.5
3.8677183983370473 5.0
3.867719518066236 4.0
3.867717171238796 4.0
3.867716251140521 1.5
3.867719627465235 4.5
3.8677189738917477 4.5
3.8677169302198564 5.0
3.8677193565275556 4.5
3.8677202205168353 4.5
3.8677206587713404 4.5
3.8677187455505253 4.0
3.8677189430150225 4.5
3.867718728189292 5.0
3.8677161454993914 5.0
3.867716885184603 3.0
3.8677172561775026 4.0
3.8677196067013564 3.0
3.8677190505744017 1.0
3.867717257338411 5.0
3.8677186256227336 5.0
3.8677207996243372 5.0
3.86771682156285 5.0
3.8677195017203623 5.0
3.8677178481735135 3.0
3.867721787435838 5.0
3.8677171584855174 5.0
3.8677228145079225 5.0
3.867713497755603 5.0
3.8677185706155264 4.0
3.867720660839478 5.0
3.867717464098247 5.0
3.867715921555953 1.0
3.867718581571532 4.0
3.867717672341054 5.0
3.8677196678752597 4.0
3.8677191638907287 4.0
3.8677160858040587 4.0
3.8677205724747328 5.0
3.867720708205615 4.0
3.8677201156881287 2.0
3.867716423197425 2.0
3.867719587544597 4.0
3.867717992337637 5.0
3.8677192855494087 4.0
3.8677155507578758 3.0
3.867719552636951 4.0
3.8677210364204018 5.0
3.867718809481633 5.0
3.8677198670711506 3.0
3.867716995386965 5.0
3.8677224177002865 1.0
3.867717027280587 5.0
3.867719233539914 3.0
3.867719886869103 3.0
3.8677187835940567 3.0
3.867716928710477 5.0
3.867719373801785 3.0
3.867719933846397 4.0
3.867720036140719 4.0
3.8677175728972415 3.0
3.867718793787208 4.0
3.867717280984884 4.0
3.8677157252945356 1.0
3.867722050516663 5.0
3.8677203381470475 5.0
3.8677177363784048 5.0
3.86772019267999 5.0
3.8677141967101343 3.0
3.8677202675089877 5.0
3.8677152920728415 5.0
3.8677199382514615 3.0
3.867718858252451 4.0
3.8677197819461986 5.0
3.867714870378708 3.0
3.8677208544040833 5.0
3.8677236901281864 5.0
3.867716468293987 5.0
3.867717383077373 4.0
3.867720139471575 5.0
3.867718521702234 4.0
3.8677197017890443 5.0
3.867719315911805 5.0
3.867722008410663 5.0
3.8677224137181905 5.0
3.8677166791231423 3.0
3.867716600225871 4.0
3.8677169687066097 5.0
3.8677195458897473 4.0
3.8677177867317987 5.0
3.86772024479197 5.0
3.867719277986416 3.0
3.867717014460386 4.0
3.8677176852981217 5.0
3.8677203885943645 3.0
3.8677176677115783 5.0
3.867717648107149 2.5
3.867719412814911 4.0
3.867719621583245 3.0
3.8677171000751 4.0
3.867716817423738 3.0
3.867720258090521 1.0
3.8677177979247848 4.5
3.867719574334928 2.5
3.867719338358659 4.5
3.8677195932868744 3.5
3.8677166815956845 2.5
3.8677174001614403 4.5
3.8677214832351083 4.5
3.8677166977988526 1.5
3.867719650394099 2.0
3.867717423621261 4.0
3.867719308925126 4.0
3.867720224231172 4.0
3.8677191439111054 3.5
3.8677167003149644 2.0
3.867717728226229 0.5
3.867719689827136 1.0
3.867717020675666 2.0
3.867720912354651 2.5
3.8677136387911024 3.5
3.867716745713831 4.0
3.867714667137335 5.0
3.8677170272473713 2.0
3.8677194454520234 4.0
3.867717517017709 0.5
3.8677211903104243 1.0
3.867719437520124 4.0
3.867717680327657 0.5
3.867720523609567 4.0
3.8677193868073596 4.0
3.8677174791241615 5.0
3.86771971137166 2.5
3.867717452020193 4.0
3.8677197407296022 1.0
3.867717746591481 4.5
3.8677187007778158 4.0
3.86771887281031 5.0
3.8677137377020743 2.5
3.8677175119228266 0.5
3.8677190045620407 2.0
3.8677191406976874 3.5
3.8677167860895536 4.5
3.8677174617737546 0.5
3.8677181886536114 3.5
3.8677202782368583 5.0
3.8677172854616573 5.0
3.8677189991259713 5.0
3.86771744832868 4.0
3.86771822763463 4.0
3.867716624150134 4.0
3.867718948685662 5.0
3.867719081044175 4.0
3.8677192262306135 3.0
3.867717811584386 4.0
3.867721343589492 4.0
3.8677188069853146 1.0
3.8677186001769397 5.0
3.867717183702682 4.0
3.8677201627234052 1.0
3.8677196477167146 5.0
3.867714715895265 4.0
3.86772030799677 4.0
3.867719930513147 5.0
3.8677182654904447 3.0
3.8677172498895964 5.0
3.8677183338326646 1.0
3.8677207710220527 4.0
3.867717620449202 3.0
3.867719533541147 5.0
3.8677193852932916 4.0
3.8677176326131137 3.0
3.867715129721914 4.0
3.867720007153256 4.0
3.8677188680347383 2.0
3.8677187324308244 3.0
3.8677199833869684 4.0
3.8677191963024757 4.0
3.867717939300934 3.0
3.867718161538711 5.0
3.8677195532050748 4.0
3.867718138117044 4.0
3.867718164682938 5.0
3.867718412199327 4.0
3.86771786455886 4.0
3.8677217358044493 1.0
3.867718936224663 4.0
3.867719768870543 5.0
3.867719138734405 3.0
3.8677172718106836 4.0
3.8677178707497686 4.0
3.867719350127194 4.0
3.867718135899989 4.0
3.8677209328952724 4.0
3.867717726452091 5.0
3.8677184882702784 5.0
3.867719899738679 2.0
3.8677184009991556 4.0
3.867719702063375 3.0
3.8677160452611434 4.0
3.867720450008525 5.0
3.8677226799597197 3.0
3.8677172085742813 5.0
3.8677197714648757 5.0
3.8677196046449134 4.0
3.867723269698287 4.0
3.8677193853680327 1.0
3.867719280465327 5.0
3.867717762964816 5.0
3.867718284804652 5.0
3.8677214935523048 4.0
3.867720509581746 4.0
3.867720333552347 4.0
3.8677167632543727 4.0
3.867719285091212 4.0
3.867717629422939 5.0
3.8677201430930825 5.0
3.8677168077472808 4.0
3.8677176296234856 5.0
3.867720015913158 4.0
3.8677176104316726 4.0
3.8677184393777346 4.0
3.8677196078824108 4.0
3.8677195238549027 4.0
3.867718451221962 4.0
3.8677198826694243 4.0
3.8677183203574854 4.0
3.8677172749854316 4.0
3.867718301281749 2.0
3.8677191974627525 3.0
3.8677180674241565 4.0
3.8677164889074844 2.0
3.8677180967186513 3.0
3.8677207651270065 3.0
3.8677176941366205 4.0
3.8677165220714893 4.0
3.8677180535261493 4.0
3.867717295441164 5.0
3.8677201922654922 3.0
3.867723402575509 4.0
3.8677182174543243 4.0
3.8677169743535145 4.0
3.8677154623265126 4.0
3.8677187497640317 4.0
3.8677160752621 3.0
3.867719241017233 2.0
3.8677202102736987 4.0
3.8677187678575304 3.0
3.867717430661495 4.0
3.867718851440367 5.0
3.8677186530416794 5.0
3.8677203561001283 3.0
3.8677205502959295 4.0
3.8677193249695803 4.0
3.8677180567942724 3.0
3.8677166105861165 5.0
3.8677167431659796 5.0
3.86771791266869 5.0
3.8677186662068572 4.0
3.8677181321018055 5.0
3.8677212917577966 5.0
3.8677150685364445 4.0
3.8677163840003628 4.0
3.867719682152627 5.0
3.867718315878898 5.0
3.8677177306713397 4.0
3.8677187151446053 5.0
3.8677161197311065 5.0
3.8677187367061983 5.0
3.8677161543291843 4.0
3.867718327597836 5.0
3.8677174555481924 4.0
3.867719074442586 4.0
3.8677216068430376 4.0
3.8677197118392836 4.0
3.867717496144214 5.0
3.867716540004495 4.0
3.8677168772992627 4.0
3.867720383561181 5.0
3.867719292093549 2.0
3.86771839064014 5.0
3.867718006169387 5.0

3.867718603343888 5.0
3.8677150861209726 2.0
3.867717913845662 4.0
3.8677187103565256 5.0
3.8677161210604205 4.0
3.86771941161213 2.0
3.867719113728268 3.0
3.867721022101507 4.0
3.8677174853083915 5.0
3.8677180855447046 3.0
3.867719197863516 5.0
3.86771939791862 4.0
3.867718315916472 4.0
3.867715058444756 2.0
3.8677194760253704 4.0
3.8677189330609107 3.0
3.8677212262587726 4.0
3.8677203027333755 3.0
3.867718759773677 3.0
3.867718550149977 4.0
3.8677190363880762 5.0
3.8677199348519333 5.0
3.8677187377019404 2.0
3.8677176987764086 2.0
3.867716784824383 4.0
3.867716366912919 5.0
3.8677195626863163 4.0
3.867715620616605 4.0
3.8677199341621247 4.0
3.8677176167661864 3.0
3.8677169308050803 4.0
3.8677214002521283 5.0
3.8677176255842634 4.0
3.8677176455908757 2.0
3.8677180421522515 4.0
3.8677186532219126 3.0
3.8677200948798767 5.0
3.8677195523876895 3.0
3.8677185123251645 5.0
3.8677188967841145 2.0
3.8677188447081665 4.0
3.8677176338341193 3.0
3.8677214432188087 4.0
3.8677209346629575 3.0
3.867716507787569 4.0
3.867717869128228 4.0
3.86771606263285 4.0
3.867718761644102 4.0
3.867719594351185 5.0
3.867717404279968 4.0
3.867718000572074 3.0
3.86771897471328 3.0
3.8677170272819357 4.0
3.867718467327867 3.0
3.8677174826654466 2.0
3.867718433549013 4.0
3.867719055969573 5.0
3.8677192665850892 4.0
3.8677181619870082 4.0
3.8677176428272175 4.0
3.867717741485258 4.0
3.867718592083569 4.0
3.867716397758008 3.0
3.867719454344103 5.0
3.8677185047959233 3.0
3.867720173966439 4.0
3.8677164842866634 4.0
3.8677193399692125 4.0
3.867719724228065 4.0
3.8677174635248073 5.0
3.867718230929842 3.0
3.8677155149643463 4.0
3.867716971528521 2.0
3.8677177123675635 2.0
3.8677174540556702 2.0
3.86771995539687 3.0
3.867717466502991 3.0
3.8677193742509908 5.0
3.867717508939161 5.0
3.867717588035547 5.0
3.867717105207628 4.0
3.867718507694329 5.0
3.8677187047526562 4.5
3.8677182597351947 5.0
3.8677176618963625 4.0
3.8677182333302653 4.0
3.8677191152975605 4.5
3.8677181072453126 5.0
3.8677188242921803 5.0
3.8677176110559532 4.0
3.8677192176401918 4.5
3.867717356646706 3.0
3.8677190157778227 2.5
3.8677187712945464 2.0
3.867718877675276 4.0
3.8677186193972473 3.5
3.8677183048478074 4.0
3.8677190260449192 2.5
3.8677181438222417 4.0
3.867718314178723 4.5
3.8677182448720107 3.5
3.86771891242377 4.0
3.867719034052551 4.0
3.8677179264624386 4.0
3.8677178486961856 3.0
3.8677160695024693 3.0
3.8677169457120906 1.0
3.867717751304775 4.0
3.8677169136705536 4.0
3.8677181289456057 3.0
3.8677190179565204 5.0
3.8677208227108 5.0
3.8677206467490235 3.0
3.8677175727952577 5.0
3.8677179206468173 4.0
3.8677194416550855 2.0
3.867718271285301 3.0
3.867718027616947 3.0
3.8677198786888676 5.0
3.867718345018612 5.0
3.867719295031274 4.0
3.8677182981379548 3.0
3.8677172043273593 3.0
3.867719475747046 5.0
3.8677181981794355 4.0
3.86771656775023 2.0
3.867720258488467 3.0
3.8677187600912273 4.0
3.8677151775436034 1.0
3.867718340444744 4.0
3.8677197273128763 3.0
3.867717922151884 4.0
3.8677197009406243 4.0
3.867719465552639 3.0
3.8677174632026627 3.0
3.867718859564348 4.0
3.8677182971399997 3.0
3.8677199780768983 3.0
3.8677200124908233 3.0
3.8677195061318725 5.0
3.8677190615049724 3.0
3.8677187891041234 3.0
3.8677201371175673 4.0
3.867717851915015 3.0
3.8677186412573774 3.0
3.8677176557036295 4.0
3.867718595449758 3.0
3.867718100300239 4.0
3.867719315484936 2.0
3.8677197373376133 4.0
3.867718999837682 3.0
3.8677181176996154 1.0
3.8677173399821445 4.0
3.867715951327462 3.0
3.8677190230092138 3.0
3.8677198614642307 1.0
3.867717419271212 2.0
3.867717493316649 3.0
3.867723157374539 5.0
3.867719104226529 4.0
3.867719462222852 1.0
3.8677206201382006 1.0
3.8677164840334863 2.0
3.8677140589456203 3.0
3.867716903699419 5.0
3.8677202009092992 4.0
3.867716972047115 3.0
3.8677175047822985 3.0
3.86772394128598 4.0
3.8677145432039444 4.0
3.867720321110516 2.0
3.8677196653849912 2.0
3.867720517564426 3.0
3.8677209374508794 3.0
3.867714366312547 1.0
3.8677171995010267 3.0
3.867716601552807 3.0
3.8677231027429038 2.0
3.86771755484822 3.0
3.8677204493113564 4.0
3.867719842486808 4.0
3.86771954647726 3.0
3.867717923958667 5.0
3.8677193074041742 4.0
3.867716585337564 3.0
3.867716148873717 3.0
3.867717293644282 3.0
3.867717956373738 1.0
3.867720510610104 4.0
3.867715088685257 3.0
3.8677199678938017 3.0
3.8677152614482213 3.0
3.867719791119976 3.0
3.86771982243389 3.0
3.8677184887699716 3.0
3.8677193453153786 3.0
3.8677135967471385 1.0
3.867716332494665 4.0
3.8677202057735802 4.0
3.867719996958653 3.0
3.8677159077423386 3.0
3.867717027789895 3.0
3.867719560621306 4.0
3.867717015826613 4.0
3.8677210577838093 4.0
3.867718945616721 3.0
3.867715668393572 3.0
3.8677206283918704 2.0
3.867719076534698 3.0
3.8677184797216952 2.0
3.8677213396785874 5.0
3.8677195894161165 3.0
3.8677186500398424 1.0
3.8677158176667183 4.0
3.8677195751316433 3.0
3.867720645816434 4.0
3.8677175998217956 3.0
3.867718124034544 5.0
3.867717638728785 3.0
3.867719529455504 3.0
3.8677195992689306 4.0
3.8677173651966132 3.0
3.8677177660994713 3.0
3.867717920227358 2.0
3.867718238410023 5.0
3.8677180862480633 4.0
3.8677192312380893 3.0
3.867719858723491 1.0
3.8677176084837988 4.0
3.86771834246385 1.0
3.8677191476163273 5.0
3.867721263278883 3.0
3.867717354581151 3.0
3.8677177892693955 5.0
3.8677224373662513 5.0
3.86771782353785 0.5
3.8677183142542977 5.0
3.867717317492307 5.0
3.867720484716002 4.0
3.8677184067471453 3.0
3.8677177483042042 5.0
3.8677170661128835 5.0
3.8677202701057367 5.0
3.867717815343974 5.0
3.867718290880656 5.0
3.867717229848264 5.0
3.867718580221454 5.0
3.8677179280012814 5.0
3.8677199435275784 5.0
3.8677196318576614 5.0
3.867720125767094 5.0
3.867721200869426 5.0
3.867718951267206 5.0
3.867718864338858 5.0
3.8677165711879056 5.0
3.8677173290035634 1.0
3.8677186543057456 5.0
3.867720356947565 5.0
3.86771908692959 5.0
3.867716994004954 5.0
3.8677184817353436 5.0
3.867719533852399 5.0
3.8677185645534036 5.0
3.8677181590950114 5.0
3.8677172592525584 5.0
3.86771829202456 5.0
3.8677190527093646 5.0
3.867716685578298 5.0
3.867721194655333 5.0
3.8677190677807247 5.0
3.867718624570471 5.0
3.86771708029696 5.0
3.8677187821483097 5.0
3.8677165820914863 5.0
3.8677182303542863 5.0
3.867721735037247 5.0
3.8677182211346315 5.0
3.8677186768004406 4.0
3.8677204552829094 5.0
3.867717835691092 5.0
3.8677204393898545 2.0
3.8677200300913817 0.5
3.86771951363377 5.0
3.867716921199767 5.0
3.8677175916434745 5.0
3.8677180082318525 5.0
3.8677184853763777 5.0
3.867720543708372 5.0
3.867720101451264 5.0
3.8677193625316955 0.5
3.8677208489775197 5.0
3.8677178437085913 5.0
3.867716909182166 3.0
3.867720059968103 0.5
3.867721005189067 5.0
3.867718620214135 5.0
3.8677194513837385 5.0
3.867715930852991 4.0
3.8677179709971257 5.0
3.8677177245628096 5.0
3.867719058050443 5.0
3.867720210943371 5.0
3.8677183703382645 5.0
3.867715805771043 4.0
3.867717560406861 0.5
3.8677183251117295 5.0
3.8677171316503074 2.0
3.867718124810303 4.0
3.867718023587545 5.0
3.8677187792303256 5.0
3.8677178580685383 1.0
3.8677173839148855 3.0
3.8677182296684536 3.0
3.8677184466634693 5.0
3.8677187906633774 4.0
3.8677192185958913 3.0
3.867718942724778 4.0
3.8677174287954377 4.0
3.8677190949420797 3.0
3.8677190728420037 3.0
3.8677201743260383 2.0
3.867717420830539 5.0
3.8677161991013165 4.0
3.8677205218969273 2.0
3.8677179767089487 3.0
3.8677185596213195 5.0
3.8677191108603806 4.0
3.8677204265850578 3.0
3.867718030127212 4.0
3.8677199140883514 4.0
3.8677204324640604 4.0
3.867717249698735 4.0
3.867717919816275 4.0
3.8677184904699056 3.0
3.8677177387280692 4.0
3.867718811828668 3.0
3.867717661487228 3.0
3.8677189118712967 5.0
3.8677182630897287 5.0
3.8677168545730765 4.0

## Stochastic Gradient Descent or Robbins Monroe Algorithm

Stochastic gradient descent involves updating separating each gradient update according to each separate observation, rather than summing over them all. It is an approximate optimization method, but it has proven convergence under certain conditions and can be much faster in practice. It is used widely by internet companies for doing machine learning in practice. For example, Facebook's ad ranking algorithm uses stochastic gradient descent.

### Question 7

Create a stochastic gradient descent version of the algorithm. Monitor the objective function after every 1000 updates to ensure that it is decreasing. When you have finished, plot the movie map and the user map in two dimensions (you can use the columns of the matrices $\mathbf{U}$ for the user map and the columns of $\mathbf{V}$ for the movie map). Provide three observations about these maps.

In [117]:
# Question 7 Code Answer

## Is Our Map Enough? Are Our Data Enough?

Is two dimensions really enough to capture the complexity of humans and their artforms? Perhaps we need even more dimensions to capture that complexity. Extending our books analogy further, consider how we should place books that have a historical timeframe as well as some geographical location. Do we really want books from the 2nd World War to sit alongside books from the Roman Empire? Books on the American invasion of Sicily in 1943 are perhaps less related to books about Carthage than those that study the Jewish Revolt from 66-70 (in the Roman Province of Judaea). So books that relate to subjects which are closer in time should be stored together. However, a student of rebellion against empire may also be interested in the relationship between the Jewish Revolt of 66-70 and the Indian Rebellion of 1857, nearly 1800 years later. Whilst the technologies are different, the psychology of the people is shared: a rebellious nation angainst their imperial masters, triggered by misrule with a religious and cultural background. To capture such complexities we would need further dimensions in our latent representation. But are further dimensions justified by the amount of data we have? Can we really understand the facets of a film that only has at most three or four ratings?

## Going Further

If you want to take this model further then you'll need more data. You can use again the MovieLens 100k data but increasing the number of users (for example, for the Steepest Descent Algorithm you can do this by modifying the variable `nUsersInExample` that was set as 10 before).

### Question 8

Use stochastic gradient descent to make a movie map for the MovieLens 100k data. Plot the map of the movies when you are finished.

In [118]:
# Code for question 8 here.